classdef TestCreateRegistrationTform < matlab.unittest.TestCase
    %TESTCREATEREGISTRATIONTFORM Unit tests for createRegistrationTform.

    properties
        TempFolder
        Fixture
    end

    methods (TestMethodSetup)
        function setup(testCase)
            testCase.TempFolder = fullfile(tempdir, ['TestCreateRegistrationTform_' char(java.util.UUID.randomUUID)]);
            testCase.Fixture = setupSyntheticRegistrationFolder(testCase.TempFolder);
        end
    end

    methods (TestMethodTeardown)
        function teardown(testCase)
            if isstruct(testCase.Fixture) && ...
                    isfield(testCase.Fixture, 'ProjectRoot') && ...
                    isfolder(testCase.Fixture.ProjectRoot)
                rmdir(testCase.Fixture.ProjectRoot, 's');
            end
            if isstruct(testCase.Fixture) && ...
                    isfield(testCase.Fixture, 'RigRoot') && ...
                    isfolder(testCase.Fixture.RigRoot)
                rmdir(testCase.Fixture.RigRoot, 's');
            end
            if isfolder(testCase.TempFolder)
                rmdir(testCase.TempFolder, 's');
            end
        end
    end

    methods (Test)
        function testPipelineManagerExecutesRegistrationNode(testCase)
            pm = buildPMForScenario(testCase.TempFolder, ...
                'createRegistrationTform', 'auto', ...
                'Parameters', struct('ShowFigure', false));
            result = pm.executePipeline('PrintSummary', false);

            testCase.verifyEqual(result.status, "completed");
            testCase.verifyTrue(isfile(fullfile(testCase.TempFolder, 'DataParams.mat')));
            S = load(fullfile(testCase.TempFolder, 'DataParams.mat'), 'DataParams');
            testCase.verifyNotEmpty(S.DataParams.registration.tform);
            testCase.verifyTrue(isfile(fullfile(testCase.TempFolder, ...
                char(string(S.DataParams.registration.qcFigureFile)))));
        end

        function testCreatesTformAndQCArtifacts(testCase)
            outFile = createRegistrationTform(testCase.TempFolder, 'ShowFigure', false);

            testCase.verifyTrue(iscell(outFile));
            testCase.verifyEqual(numel(outFile), 3);
            for i = 1:numel(outFile)
                testCase.verifyTrue(isfile(fullfile(testCase.TempFolder, outFile{i})));
            end

            S = load(fullfile(testCase.TempFolder, 'DataParams.mat'), 'DataParams');
            DP = S.DataParams;
            validateDataParams(DP);
            testCase.verifyFalse(DP.registration.isRegistered);
            testCase.verifyFalse(DP.registration.isReviewed);
            testCase.verifyNotEmpty(DP.registration.tform);
            testCase.verifyEqual(char(string(DP.registration.qcFigureFile)), outFile{2});
            testCase.verifyEqual(char(string(DP.registration.qcPreviewImageFile)), outFile{3});
            testCase.verifyGreaterThan(DP.registration.qcMetrics.MIAfter, DP.registration.qcMetrics.MIBefore);
            testCase.verifyEqual( ...
                DP.registration.referenceImage, ...
                testCase.Fixture.ReferenceImage);
            testCase.verifyEqual( ...
                DP.registration.referenceFile, ...
                testCase.Fixture.ManagedReference.absolutePath);
            testCase.verifyEqual( ...
                DP.registration.imageReferenceUUID, ...
                testCase.Fixture.ImageReferenceUUID);
            testCase.verifyEqual( ...
                DP.registration.imageReferenceChecksum, ...
                testCase.Fixture.ManagedReference.checksum);
            testCase.verifyEqual( ...
                DP.registration.referenceDescription, ...
                testCase.Fixture.ManagedDescription);
            testCase.verifyEqual( ...
                DP.registration.source, ...
                fullfile(testCase.TempFolder, 'green.dat'));
            testCase.verifyEmpty(DP.registration.resourceUUID);
        end

        function testSpecificUseFile(testCase)
            outFile = createRegistrationTform(testCase.TempFolder, 'UseFile', 'red.dat', 'ShowFigure', false);
            testCase.verifyTrue(iscell(outFile));
            S = load(fullfile(testCase.TempFolder, 'DataParams.mat'), 'DataParams');
            testCase.verifyEqual( ...
                char(string(S.DataParams.registration.referenceFile)), ...
                testCase.Fixture.ManagedReference.absolutePath);
            testCase.verifyEqual( ...
                char(string(S.DataParams.registration.source)), ...
                fullfile(testCase.TempFolder, 'red.dat'));
        end

        function testOtherLayoutsAreRefused(testCase)
            layouts = {{'Y','X','T','E'}, [6 5 4 2]; {'Y','X','E'}, [6 5 3]; {'Y','X'}, [6 5]};
            for k = 1:size(layouts, 1)
                f = fullfile(testCase.TempFolder, 'layout.dat');
                writeTestDat(f, rand([layouts{k, 2}, 1], 'single'), 10, 5, ...
                    'DimNames', layouts{k, 1});
                testCase.verifyError(@() createRegistrationTform(testCase.TempFolder, ...
                    'UseFile', 'layout.dat', 'ShowFigure', false), ...
                    'Umitoolbox:createRegistrationTform:unsupportedLayout');
            end
        end

        function testAutoUsesReferenceSourceInsteadOfDerivedDat(testCase)
            derivedData = testCase.Fixture.RedData;
            testCase.writeSingleDat( ...
                fullfile(testCase.TempFolder, 'GSR.dat'), derivedData, 10, 20);

            createRegistrationTform( ...
                testCase.TempFolder, 'ShowFigure', false);

            DataParams = loadDataParams(testCase.TempFolder);
            testCase.verifyEqual( ...
                char(string(DataParams.registration.source)), ...
                fullfile(testCase.TempFolder, 'green.dat'));
        end

        function testAutoMissingReferenceSourceFailsWithoutMutation(testCase)
            testCase.updateActiveReferenceSourceFile('');

            testCase.verifyPreflightFailure( ...
                @() createRegistrationTform( ...
                testCase.TempFolder, 'ShowFigure', false), ...
                ['Umitoolbox:createRegistrationTform:' ...
                 'AutoSourceFileUnavailable']);
        end

        function testNewActiveReferenceSupersedesFolderSnapshot(testCase)
            DataParams = loadDataParams(testCase.TempFolder);
            DataParams.registration.referenceDescription = ...
                'Stale folder-local reference that must not be used';
            DataParams.registration.referenceFile = 'legacy_reference.mat';
            DataParams.registration.referenceImage = ...
                fliplr(testCase.Fixture.ReferenceImage);
            saveDataParams(testCase.TempFolder, DataParams);

            secondImage = 1.5 .* testCase.Fixture.ReferenceImage;
            [secondUUID, secondResource] = ...
                testCase.addAndActivateReference( ...
                secondImage, 'Second active reference');

            createRegistrationTform( ...
                testCase.TempFolder, 'ShowFigure', false);

            DataParams = loadDataParams(testCase.TempFolder);
            testCase.verifyEqual( ...
                DataParams.registration.referenceImage, secondImage);
            testCase.verifyEqual( ...
                DataParams.registration.imageReferenceUUID, secondUUID);
            testCase.verifyEqual( ...
                DataParams.registration.imageReferenceChecksum, ...
                secondResource.checksum);
            testCase.verifyEqual( ...
                DataParams.registration.referenceFile, ...
                secondResource.absolutePath);
        end

        function testNoActiveReferenceDoesNotUseAvailableResource(testCase)
            testCase.clearActiveReferencePointer();

            testCase.verifyPreflightFailure( ...
                @() createRegistrationTform( ...
                testCase.TempFolder, 'ShowFigure', false), ...
                'Umitoolbox:createRegistrationTform:NoActiveImageReference');
        end

        function testMissingManagedReferenceFileDoesNotMutateFolder(testCase)
            delete(testCase.Fixture.ManagedReference.absolutePath);

            testCase.verifyPreflightFailure( ...
                @() createRegistrationTform( ...
                testCase.TempFolder, 'ShowFigure', false), ...
                ['Umitoolbox:createRegistrationTform:' ...
                 'ActiveImageReferenceResolutionFailed']);
        end

        function testInvalidManagedReferencePayloadDoesNotMutateFolder(testCase)
            managedPath = testCase.Fixture.ManagedReference.absolutePath;
            loaded = load(managedPath, 'ImageReference', '-mat');
            ImageReference = rmfield(loaded.ImageReference, 'image');
            save(managedPath, 'ImageReference', '-mat');

            SubjectInfo = testCase.Fixture.Store.getSubjectInfo( ...
                testCase.Fixture.SubjectID);
            idx = find(strcmp( ...
                {SubjectInfo.resourceRegistry.uuid}, ...
                testCase.Fixture.ImageReferenceUUID), 1, 'first');
            SubjectInfo.resourceRegistry(idx).checksum = ...
                computeFileChecksum(managedPath);
            SubjectInfo.resourceRegistry(idx).modifiedOn = datetime('now');
            SubjectInfo.modifiedOn = datetime('now');
            testCase.saveSubjectInfo(SubjectInfo);

            testCase.verifyPreflightFailure( ...
                @() createRegistrationTform( ...
                testCase.TempFolder, 'ShowFigure', false), ...
                ['Umitoolbox:createRegistrationTform:' ...
                 'InvalidImageReferencePayload']);
        end

        function testMissingBindingDoesNotMutateFolder(testCase)
            bindingPath = fullfile( ...
                testCase.TempFolder, ...
                UMITProjectStore.getProjectBindingFileName());
            delete(bindingPath);

            testCase.verifyPreflightFailure( ...
                @() createRegistrationTform( ...
                testCase.TempFolder, 'ShowFigure', false), ...
                ['Umitoolbox:createRegistrationTform:' ...
                 'BindingResolutionFailed']);
        end

        function testMalformedBindingDoesNotMutateFolder(testCase)
            bindingPath = fullfile( ...
                testCase.TempFolder, ...
                UMITProjectStore.getProjectBindingFileName());
            InvalidBinding = struct('unexpectedField', true);
            save(bindingPath, 'InvalidBinding', '-mat');

            testCase.verifyPreflightFailure( ...
                @() createRegistrationTform( ...
                testCase.TempFolder, 'ShowFigure', false), ...
                ['Umitoolbox:createRegistrationTform:' ...
                 'BindingResolutionFailed']);
        end

        function testInconsistentBindingPathDoesNotMutateFolder(testCase)
            schema = getUMITProjectSchema();
            sessionPath = fullfile( ...
                testCase.Fixture.ProjectRoot, ...
                schema.folders.subjects, ...
                testCase.Fixture.SubjectID, ...
                schema.folders.sessions, ...
                testCase.Fixture.SessionID, ...
                schema.files.sessionMetadata);
            loaded = load(sessionPath, ...
                schema.metadataVariables.session, '-mat');
            SessionInfo = loaded.(schema.metadataVariables.session);
            SessionInfo.processedDataFolder = fullfile( ...
                testCase.TempFolder, 'different_location');
            SessionInfo.modifiedOn = datetime('now');
            saveMatAtomic(sessionPath, ...
                schema.metadataVariables.session, SessionInfo);

            testCase.verifyPreflightFailure( ...
                @() createRegistrationTform( ...
                testCase.TempFolder, 'ShowFigure', false), ...
                ['Umitoolbox:createRegistrationTform:' ...
                 'BindingResolutionFailed']);
        end

        function testLoadAndSaveNormalizeImageReferenceProvenance(testCase)
            dataParamsPath = fullfile( ...
                testCase.TempFolder, 'DataParams.mat');
            loaded = load(dataParamsPath, 'DataParams', '-mat');
            DataParams = loaded.DataParams;
            DataParams.registration = rmfield( ...
                DataParams.registration, ...
                {'imageReferenceUUID', 'imageReferenceChecksum'});
            save(dataParamsPath, 'DataParams', '-mat');

            DataParams = loadDataParams(testCase.TempFolder);
            testCase.verifyEmpty( ...
                DataParams.registration.imageReferenceUUID);
            testCase.verifyEmpty( ...
                DataParams.registration.imageReferenceChecksum);

            saveDataParams(testCase.TempFolder, DataParams);
            persisted = load(dataParamsPath, 'DataParams', '-mat');
            testCase.verifyTrue(isfield( ...
                persisted.DataParams.registration, ...
                'imageReferenceUUID'));
            testCase.verifyTrue(isfield( ...
                persisted.DataParams.registration, ...
                'imageReferenceChecksum'));
        end

        function testPipelineInfoDescribesManagedReferenceRequirement(testCase)
            info = createRegistrationTform('pipelineInfo');

            testCase.verifySubstring(info.description, ...
                'active project-managed Image Reference');
            saveFolderInput = info.inputs(strcmp( ...
                {info.inputs.name}, 'SaveFolder'));
            testCase.verifySubstring(saveFolderInput.description, ...
                'active managed Image Reference');
            useFileInput = info.parameters(strcmp( ...
                {info.parameters.name}, 'UseFile'));
            testCase.verifySubstring(useFileInput.description, ...
                'ImageReference.sourceFile');
            testCase.verifySubstring(useFileInput.description, ...
                'do not fall back');
        end
    end

    methods (Access = private)
        function [resourceUUID, resource] = addAndActivateReference( ...
                testCase, imageData, description)
            ProjectInfo = testCase.Fixture.Store.getProjectInfo();
            ImageReference = genImageReferenceStruct( ...
                imageData, ...
                'Name', description, ...
                'ProjectUUID', ProjectInfo.projectUUID, ...
                'ProjectName', ProjectInfo.projectName, ...
                'SubjectUUID', testCase.Fixture.SubjectUUID, ...
                'SubjectID', testCase.Fixture.SubjectID, ...
                'SessionUUID', testCase.Fixture.SessionUUID, ...
                'SessionID', testCase.Fixture.SessionID, ...
                'Description', description, ...
                'SourceFolder', testCase.TempFolder, ...
                'SourceFile', fullfile(testCase.TempFolder, 'green.dat'), ...
                'SourceType', 'synthetic-test', ...
                'CreatedBy', 'TestCreateRegistrationTform');
            sourcePath = fullfile(testCase.TempFolder, ...
                ['reference_' char(java.util.UUID.randomUUID()) '.mat']);
            save(sourcePath, 'ImageReference', '-mat');

            resourceUUID = testCase.Fixture.Store.addImageReference( ...
                testCase.Fixture.SubjectID, sourcePath, struct( ...
                'displayName', description, ...
                'description', description));
            testCase.Fixture.Store.setActiveImageReference( ...
                testCase.Fixture.SubjectID, resourceUUID);
            resource = testCase.Fixture.Store.getResource(resourceUUID);
        end

        function clearActiveReferencePointer(testCase)
            SubjectInfo = testCase.Fixture.Store.getSubjectInfo( ...
                testCase.Fixture.SubjectID);
            idx = find(strcmp( ...
                {SubjectInfo.resourceRegistry.uuid}, ...
                testCase.Fixture.ImageReferenceUUID), 1, 'first');
            SubjectInfo.resourceRegistry(idx).status = 'available';
            SubjectInfo.resourceRegistry(idx).modifiedOn = datetime('now');
            SubjectInfo.activeImageReferenceUUID = '';
            SubjectInfo.modifiedOn = datetime('now');
            testCase.saveSubjectInfo(SubjectInfo);
        end

        function saveSubjectInfo(testCase, SubjectInfo)
            schema = getUMITProjectSchema();
            subjectPath = fullfile( ...
                testCase.Fixture.ProjectRoot, ...
                schema.folders.subjects, ...
                testCase.Fixture.SubjectID, ...
                schema.files.subjectMetadata);
            saveMatAtomic(subjectPath, ...
                schema.metadataVariables.subject, SubjectInfo);
        end

        function updateActiveReferenceSourceFile(testCase, sourceFile)
            managedPath = testCase.Fixture.ManagedReference.absolutePath;
            loaded = load(managedPath, 'ImageReference', '-mat');
            ImageReference = loaded.ImageReference;
            ImageReference.sourceFile = sourceFile;
            save(managedPath, 'ImageReference', '-mat');

            SubjectInfo = testCase.Fixture.Store.getSubjectInfo( ...
                testCase.Fixture.SubjectID);
            idx = find(strcmp( ...
                {SubjectInfo.resourceRegistry.uuid}, ...
                testCase.Fixture.ImageReferenceUUID), 1, 'first');
            SubjectInfo.resourceRegistry(idx).checksum = ...
                computeFileChecksum(managedPath);
            SubjectInfo.resourceRegistry(idx).modifiedOn = datetime('now');
            SubjectInfo.modifiedOn = datetime('now');
            testCase.saveSubjectInfo(SubjectInfo);
        end

        function writeSingleDat(~, filePath, data, frameRateHz, exposureMsec)
            % Headered input (.dat header Phase 5a).
            writeTestDat(filePath, single(data), frameRateHz, exposureMsec);
        end

        function verifyPreflightFailure(testCase, operation, errorID)
            dataParamsPath = fullfile( ...
                testCase.TempFolder, 'DataParams.mat');
            checksumBefore = computeFileChecksum(dataParamsPath);
            qcBefore = dir(fullfile( ...
                testCase.TempFolder, 'registrationQC_*'));

            testCase.verifyError(operation, errorID);

            testCase.verifyEqual( ...
                computeFileChecksum(dataParamsPath), checksumBefore);
            qcAfter = dir(fullfile( ...
                testCase.TempFolder, 'registrationQC_*'));
            testCase.verifyEqual({qcAfter.name}, {qcBefore.name});
        end
    end
end
