function schema = getUMITRigSchema(version)
%GETUMITRIGSCHEMA Return the versioned centralized UMIT rig-store schema.
%
%   schema = getUMITRigSchema()
%   schema = getUMITRigSchema(version)
%
%   Returns the versioned schema used by UMITRigStore to create, modify,
%   archive, rename, and validate centralized rig folders.
%
%   A rig describes one physical imaging setup (cameras, filters, dual-camera
%   coregistration). Rigs are independent of any project: a
%   project/session references a rig by rigUUID/rigID, but never owns its
%   folder or metadata. This mirrors the split between UMITProjectStore's own
%   project metadata and the external imaging SaveFolders it references.
%
%   Inputs:
%       version - Numeric scalar schema version. Default: 1.
%
%   Output:
%       schema  - Structure containing canonical folder names, resource
%                 definitions, naming rules, and validation rules.
%
%   Notes:
%       - Store only schema.version in rig metadata. The complete schema
%         definition remains centralized in this function.
%       - Managed identifiers are case-insensitive for uniqueness checks
%         to preserve compatibility with Windows filesystems.

if nargin < 1 || isempty(version)
    version = 2;
end

if ~isnumeric(version) || ~isscalar(version) || ~isfinite(version) || ...
        version < 1 || mod(version, 1) ~= 0
    error('Umitoolbox:getUMITRigSchema:invalidVersion', ...
        'Schema version must be a positive integer scalar.');
end

switch version
    case 1
        schema = struct();
        schema.version = 1;

        % -----------------------------------------------------------------
        % Canonical rig folders and metadata files
        % -----------------------------------------------------------------
        schema.folders = struct();
        schema.folders.internal = '.umit';
        schema.folders.transactions = 'transactions';
        schema.folders.recovery = 'recovery';
        schema.folders.logs = 'logs';
        schema.folders.lock = 'rig.lock';
        schema.folders.transforms = 'transforms';
        schema.folders.cameraCoregistration = 'camera-coregistration';
        schema.folders.calibrationFiles = 'calibration-files';
        schema.folders.active = 'active';
        schema.folders.archive = 'archive';

        schema.files = struct();
        schema.files.rigMetadata = 'rig.mat';
        schema.files.lockMetadata = 'lockInfo.mat';

        schema.metadataVariables = struct();
        schema.metadataVariables.rig = 'RigInfo';

        schema.requiredInternalFolders = { ...
            schema.folders.transactions, ...
            schema.folders.recovery, ...
            schema.folders.logs};

        % Human-readable canonical template used by apps and diagnostics.
        schema.pathTemplates = struct();
        schema.pathTemplates.rig = '<RigID>';
        schema.pathTemplates.cameraCoregistration = ...
            'transforms/camera-coregistration/<State>';
        schema.pathTemplates.calibrationFiles = 'calibration-files/<State>';

        % -----------------------------------------------------------------
        % Managed ID rules (shared shape with getUMITProjectSchema)
        % -----------------------------------------------------------------
        schema.namingRules = struct();
        schema.namingRules.idPattern = '^[A-Za-z0-9][A-Za-z0-9_-]*$';
        schema.namingRules.maxIDLength = 64;
        schema.namingRules.caseSensitive = false;
        schema.namingRules.uuidPattern = ...
            '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$';
        schema.namingRules.reservedPrefixes = {'.', '__', '.umit'};
        schema.namingRules.reservedNames = { ...
            '.', '..', 'CON', 'PRN', 'AUX', 'NUL', ...
            'COM1', 'COM2', 'COM3', 'COM4', 'COM5', ...
            'COM6', 'COM7', 'COM8', 'COM9', ...
            'LPT1', 'LPT2', 'LPT3', 'LPT4', 'LPT5', ...
            'LPT6', 'LPT7', 'LPT8', 'LPT9'};

        % Files created automatically by operating systems are ignored by
        % strict unregistered-item checks.
        schema.allowedIncidentalNames = { ...
            'desktop.ini', 'thumbs.db', '.DS_Store'};

        % -----------------------------------------------------------------
        % Resource definitions
        % -----------------------------------------------------------------
        schema.resourceStates = {'available', 'active', 'archived'};

        schema.resourceTypes = struct();

        schema.resourceTypes.cameraCoregistration = struct( ...
            'filePrefix', 'CameraCoregistration', ...
            'allowedExtensions', {{'.mat'}}, ...
            'activePointerField', 'activeCoregistrationUUID', ...
            'relativeFolderParts', {{ ...
                schema.folders.transforms, ...
                schema.folders.cameraCoregistration}}, ...
            'requiredVariable', '', ...
            'validatorFunction', '');

        schema.resourceTypes.calibrationFile = struct( ...
            'filePrefix', 'Calibration', ...
            'allowedExtensions', {{'.mat'}}, ...
            'activePointerField', 'activeCalibrationFileUUID', ...
            'relativeFolderParts', {{schema.folders.calibrationFiles}}, ...
            'requiredVariable', '', ...
            'validatorFunction', '');

        % -----------------------------------------------------------------
        % Required metadata fields
        % -----------------------------------------------------------------
        schema.requiredRigFields = { ...
            'schemaVersion', ...
            'uuid', ...
            'rigID', ...
            'displayName', ...
            'description', ...
            'createdOn', ...
            'modifiedOn', ...
            'isDefault', ...
            'activeCoregistrationUUID', ...
            'activeCalibrationFileUUID', ...
            'resourceRegistry'};

        schema.resourceRecordFields = { ...
            'uuid', ...
            'type', ...
            'fileName', ...
            'relativePath', ...
            'displayName', ...
            'description', ...
            'createdOn', ...
            'modifiedOn', ...
            'status', ...
            'archivedOn', ...
            'checksum', ...
            'sourceFile'};

        % Editable fields exclude immutable UUIDs and managed identifiers.
        schema.editableFields = struct();
        schema.editableFields.rig = {'displayName', 'description', 'isDefault'};
        schema.editableFields.resource = {'displayName', 'description'};

    case 2
        % Adds three fields to the version-1 rig record, all additive:
        %   metadata   - open struct reserved for future rig-scoped data
        %                (camera names, per-camera info, filter spectral
        %                profiles, ...) that hasn't been designed yet.
        %                Never validated against a fixed shape; callers
        %                merge new keys in via updateRigMetadata.
        %   status     - 'active' | 'archived'. Rigs are soft-deleted via
        %                archiveRig, never removed, so sessions that
        %                reference a rigID/rigUUID keep resolving.
        %   archivedOn - Timestamp set when status becomes 'archived'.
        %
        % Version-1 rig records on disk are upgraded to this shape lazily
        % in memory the next time they are loaded (see
        % UMITRigStore.iUpgradeRigInfo) -- no bulk migration pass is
        % required, and the upgraded shape persists automatically the next
        % time anything writes that rig's metadata.
        schema = struct();
        schema.version = 2;

        % -----------------------------------------------------------------
        % Canonical rig folders and metadata files
        % -----------------------------------------------------------------
        schema.folders = struct();
        schema.folders.internal = '.umit';
        schema.folders.transactions = 'transactions';
        schema.folders.recovery = 'recovery';
        schema.folders.logs = 'logs';
        schema.folders.lock = 'rig.lock';
        schema.folders.transforms = 'transforms';
        schema.folders.cameraCoregistration = 'camera-coregistration';
        schema.folders.calibrationFiles = 'calibration-files';
        schema.folders.active = 'active';
        schema.folders.archive = 'archive';

        schema.files = struct();
        schema.files.rigMetadata = 'rig.mat';
        schema.files.lockMetadata = 'lockInfo.mat';

        schema.metadataVariables = struct();
        schema.metadataVariables.rig = 'RigInfo';

        schema.requiredInternalFolders = { ...
            schema.folders.transactions, ...
            schema.folders.recovery, ...
            schema.folders.logs};

        % Human-readable canonical template used by apps and diagnostics.
        schema.pathTemplates = struct();
        schema.pathTemplates.rig = '<RigID>';
        schema.pathTemplates.cameraCoregistration = ...
            'transforms/camera-coregistration/<State>';
        schema.pathTemplates.calibrationFiles = 'calibration-files/<State>';

        % -----------------------------------------------------------------
        % Managed ID rules (shared shape with getUMITProjectSchema)
        % -----------------------------------------------------------------
        schema.namingRules = struct();
        schema.namingRules.idPattern = '^[A-Za-z0-9][A-Za-z0-9_-]*$';
        schema.namingRules.maxIDLength = 64;
        schema.namingRules.caseSensitive = false;
        schema.namingRules.uuidPattern = ...
            '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$';
        schema.namingRules.reservedPrefixes = {'.', '__', '.umit'};
        schema.namingRules.reservedNames = { ...
            '.', '..', 'CON', 'PRN', 'AUX', 'NUL', ...
            'COM1', 'COM2', 'COM3', 'COM4', 'COM5', ...
            'COM6', 'COM7', 'COM8', 'COM9', ...
            'LPT1', 'LPT2', 'LPT3', 'LPT4', 'LPT5', ...
            'LPT6', 'LPT7', 'LPT8', 'LPT9'};

        % Files created automatically by operating systems are ignored by
        % strict unregistered-item checks.
        schema.allowedIncidentalNames = { ...
            'desktop.ini', 'thumbs.db', '.DS_Store'};

        % -----------------------------------------------------------------
        % Resource definitions
        % -----------------------------------------------------------------
        schema.resourceStates = {'available', 'active', 'archived'};

        schema.resourceTypes = struct();

        schema.resourceTypes.cameraCoregistration = struct( ...
            'filePrefix', 'CameraCoregistration', ...
            'allowedExtensions', {{'.mat'}}, ...
            'activePointerField', 'activeCoregistrationUUID', ...
            'relativeFolderParts', {{ ...
                schema.folders.transforms, ...
                schema.folders.cameraCoregistration}}, ...
            'requiredVariable', '', ...
            'validatorFunction', '');

        schema.resourceTypes.calibrationFile = struct( ...
            'filePrefix', 'Calibration', ...
            'allowedExtensions', {{'.mat'}}, ...
            'activePointerField', 'activeCalibrationFileUUID', ...
            'relativeFolderParts', {{schema.folders.calibrationFiles}}, ...
            'requiredVariable', '', ...
            'validatorFunction', '');

        % -----------------------------------------------------------------
        % Rig-level status (soft-delete, distinct from per-resource status)
        % -----------------------------------------------------------------
        schema.rigStatuses = {'active', 'archived'};

        % -----------------------------------------------------------------
        % Required metadata fields
        % -----------------------------------------------------------------
        schema.requiredRigFields = { ...
            'schemaVersion', ...
            'uuid', ...
            'rigID', ...
            'displayName', ...
            'description', ...
            'createdOn', ...
            'modifiedOn', ...
            'isDefault', ...
            'status', ...
            'archivedOn', ...
            'metadata', ...
            'activeCoregistrationUUID', ...
            'activeCalibrationFileUUID', ...
            'resourceRegistry'};

        schema.resourceRecordFields = { ...
            'uuid', ...
            'type', ...
            'fileName', ...
            'relativePath', ...
            'displayName', ...
            'description', ...
            'createdOn', ...
            'modifiedOn', ...
            'status', ...
            'archivedOn', ...
            'checksum', ...
            'sourceFile'};

        % Editable fields exclude immutable UUIDs and managed identifiers.
        % 'status'/'archivedOn' are excluded deliberately -- they change
        % only through the dedicated archiveRig method, never through a
        % generic metadata update, mirroring how resource status changes
        % only through archiveResource/restoreResource.
        schema.editableFields = struct();
        schema.editableFields.rig = {'displayName', 'description', 'isDefault', 'metadata'};
        schema.editableFields.resource = {'displayName', 'description'};

    otherwise
        error('Umitoolbox:getUMITRigSchema:unsupportedVersion', ...
            'Unsupported UMIT rig schema version: %g.', version);
end

end
