function schema = getUMITProjectSchema(version)
%GETUMITPROJECTSCHEMA Return the centralized UMIT project-folder schema.
%
%   schema = getUMITProjectSchema()
%   schema = getUMITProjectSchema(version)
%
%   Returns the versioned schema used by UMITProjectStore to create,
%   modify, archive, rename, and validate centralized UMIT project folders.
%
%   Inputs:
%       version - Numeric scalar schema version. Default: 1.
%
%   Output:
%       schema  - Structure containing canonical folder names, path
%                 templates, node definitions, metadata requirements,
%                 naming rules, resource definitions, and validation rules.
%
%   Notes:
%       - The centralized project folder stores metadata, image-reference
%         files, and session registration-transform files only.
%       - Imaging data remains external and is referenced from metadata.
%       - Rigs are independent of any project: rig metadata and rig-owned
%         resources (dual-camera coregistration, calibration files) live in
%         the separate UMITRigStore/getUMITRigSchema. A session only keeps a
%         rigUUID/rigID pointer to an external rig -- it never owns one.
%       - Store only schema.version in project metadata. The complete
%         schema definition remains centralized in this function.
%       - Managed identifiers are case-insensitive for uniqueness checks
%         to preserve compatibility with Windows filesystems.

if nargin < 1 || isempty(version)
    version = 1;
end

if ~isnumeric(version) || ~isscalar(version) || ~isfinite(version) || ...
        version < 1 || mod(version, 1) ~= 0
    error('Umitoolbox:getUMITProjectSchema:invalidVersion', ...
        'Schema version must be a positive integer scalar.');
end

switch version
    case 1
        schema = struct();
        schema.version = 1;

        % -----------------------------------------------------------------
        % Canonical project folders and metadata files
        % -----------------------------------------------------------------
        schema.folders = struct();
        schema.folders.internal = '.umit';
        schema.folders.transactions = 'transactions';
        schema.folders.recovery = 'recovery';
        schema.folders.logs = 'logs';
        schema.folders.lock = 'project.lock';
        schema.folders.subjects = 'subjects';
        schema.folders.references = 'references';
        schema.folders.image = 'image';
        schema.folders.sessions = 'sessions';
        schema.folders.transforms = 'transforms';
        schema.folders.registration = 'registration';
        schema.folders.active = 'active';
        schema.folders.archive = 'archive';

        schema.files = struct();
        schema.files.projectMetadata = 'project.mat';
        schema.files.subjectMetadata = 'subject.mat';
        schema.files.sessionMetadata = 'session.mat';
        schema.files.lockMetadata = 'lockInfo.mat';
        schema.files.projectBinding = 'UMITProjectBinding.umitlink';

        schema.metadataVariables = struct();
        schema.metadataVariables.project = 'ProjectInfo';
        schema.metadataVariables.subject = 'SubjectInfo';
        schema.metadataVariables.session = 'SessionInfo';
        schema.metadataVariables.projectBinding = 'ProjectBinding';

        schema.projectBinding = struct();
        schema.projectBinding.version = 1;
        schema.projectBinding.folderRoles = { ...
            'rawDataFolder', ...
            'processedDataFolder'};

        schema.requiredProjectBindingFields = { ...
            'version', ...
            'bindingUUID', ...
            'projectUUID', ...
            'subjectUUID', ...
            'sessionUUID', ...
            'folderRole', ...
            'createdOn', ...
            'modifiedOn'};

        schema.requiredTopFolders = { ...
            schema.folders.internal, ...
            schema.folders.subjects};

        schema.requiredInternalFolders = { ...
            schema.folders.transactions, ...
            schema.folders.recovery, ...
            schema.folders.logs};

        % Human-readable canonical templates used by apps and diagnostics.
        schema.pathTemplates = struct();
        schema.pathTemplates.subject = ...
            'subjects/<SubjectID>';
        schema.pathTemplates.subjectImageReferences = ...
            'subjects/<SubjectID>/references/image/<State>';
        schema.pathTemplates.session = ...
            'subjects/<SubjectID>/sessions/<SessionID>';
        schema.pathTemplates.sessionRegistration = ...
            ['subjects/<SubjectID>/sessions/<SessionID>/' ...
             'transforms/registration/<State>'];

        schema.nodeTypes = struct();
        schema.nodeTypes.project = struct( ...
            'metadataFile', schema.files.projectMetadata, ...
            'allowedChildren', {{ ...
                schema.folders.internal, ...
                schema.folders.subjects}});
        schema.nodeTypes.subject = struct( ...
            'metadataFile', schema.files.subjectMetadata, ...
            'parentType', 'project', ...
            'allowedChildren', {{ ...
                schema.folders.references, ...
                schema.folders.sessions}});
        schema.nodeTypes.session = struct( ...
            'metadataFile', schema.files.sessionMetadata, ...
            'parentType', 'subject', ...
            'allowedChildren', {{schema.folders.transforms}});

        % -----------------------------------------------------------------
        % Managed ID rules
        % -----------------------------------------------------------------
        schema.namingRules = struct();
        schema.namingRules.idPattern = '^[A-Za-z0-9][A-Za-z0-9_-]*$';
        schema.namingRules.maxIDLength = 64;
        schema.namingRules.caseSensitive = false;
        schema.namingRules.uuidPattern = ...
            '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$';
        schema.namingRules.reservedPrefixes = {'.', '__', '.umit'};
        schema.namingRules.reservedNames = { ...
            '.', '..', 'CON', 'PRN', 'AUX', 'NUL', ...
            'COM1', 'COM2', 'COM3', 'COM4', 'COM5', ...
            'COM6', 'COM7', 'COM8', 'COM9', ...
            'LPT1', 'LPT2', 'LPT3', 'LPT4', 'LPT5', ...
            'LPT6', 'LPT7', 'LPT8', 'LPT9'};

        % Files created automatically by operating systems are ignored by
        % strict unregistered-item checks.
        schema.allowedIncidentalNames = { ...
            'desktop.ini', 'thumbs.db', '.DS_Store'};

        % -----------------------------------------------------------------
        % Resource definitions
        % -----------------------------------------------------------------
        schema.resourceStates = {'available', 'active', 'archived'};

        schema.resourceTypes = struct();

        schema.resourceTypes.imageReference = struct( ...
            'ownerType', 'subject', ...
            'filePrefix', 'ImageReference', ...
            'allowedExtensions', {{'.mat'}}, ...
            'activePointerField', 'activeImageReferenceUUID', ...
            'relativeFolderParts', {{ ...
                schema.folders.references, ...
                schema.folders.image}}, ...
            'requiredVariable', 'ImageReference', ...
            'validatorFunction', 'validateImageReferenceStruct');

        schema.resourceTypes.registrationTransform = struct( ...
            'ownerType', 'session', ...
            'filePrefix', 'SessionToReference', ...
            'allowedExtensions', {{'.mat'}}, ...
            'activePointerField', 'activeRegistrationTransformUUID', ...
            'relativeFolderParts', {{ ...
                schema.folders.transforms, ...
                schema.folders.registration}}, ...
            'requiredVariable', '', ...
            'validatorFunction', '');

        % cameraCoregistration and calibrationFile resource types moved to
        % the independent UMITRigStore/getUMITRigSchema -- rigs are no
        % longer owned by a project, see requiredSessionFields.rigUUID/rigID
        % for the pointer a session keeps to an external rig.

        % -----------------------------------------------------------------
        % Required metadata fields
        % -----------------------------------------------------------------
        schema.requiredProjectFields = { ...
            'schemaVersion', ...
            'projectUUID', ...
            'projectName', ...
            'description', ...
            'createdOn', ...
            'modifiedOn', ...
            'subjectRegistry'};

        schema.requiredSubjectFields = { ...
            'schemaVersion', ...
            'uuid', ...
            'subjectID', ...
            'displayName', ...
            'description', ...
            'createdOn', ...
            'modifiedOn', ...
            'activeImageReferenceUUID', ...
            'sessionRegistry', ...
            'resourceRegistry'};

        schema.requiredSessionFields = { ...
            'schemaVersion', ...
            'uuid', ...
            'sessionID', ...
            'subjectUUID', ...
            'subjectID', ...
            'displayName', ...
            'description', ...
            'acquisitionDate', ...
            'rawDataFolder', ...
            'rawDataBindingUUID', ...
            'processedDataFolder', ...
            'processedDataBindingUUID', ...
            'rigUUID', ...
            'rigID', ...
            'createdOn', ...
            'modifiedOn', ...
            'activeRegistrationTransformUUID', ...
            'resourceRegistry'};

        schema.registryFields = { ...
            'uuid', ...
            'id', ...
            'displayName', ...
            'relativePath'};

        schema.resourceRecordFields = { ...
            'uuid', ...
            'type', ...
            'fileName', ...
            'relativePath', ...
            'displayName', ...
            'description', ...
            'createdOn', ...
            'modifiedOn', ...
            'status', ...
            'archivedOn', ...
            'checksum', ...
            'sourceFile'};

        % Editable fields exclude immutable UUIDs and managed identifiers.
        schema.editableFields = struct();
        schema.editableFields.subject = {'displayName', 'description'};
        schema.editableFields.session = { ...
            'displayName', ...
            'description', ...
            'acquisitionDate', ...
            'rigUUID', ...
            'rigID'};
        schema.editableFields.resource = {'displayName', 'description'};

    otherwise
        error('Umitoolbox:getUMITProjectSchema:unsupportedVersion', ...
            'Unsupported UMIT project schema version: %g.', version);
end

end
