function outData = run_Ana_Speckle(SaveFolder, data, varargin)
%RUN_ANA_SPECKLE Wrapper around Ana_Speckle (blood flow from speckle data).
%
%   outData = run_Ana_Speckle(SaveFolder, data)
%   outData = run_Ana_Speckle(SaveFolder, data, 'bNormalize', true)
%
%   This wrapper runs Ana_Speckle in its file-based (low-RAM) mode.
%
%   Inputs:
%       SaveFolder - Folder of the speckle file and of the .dat output.
%       data       - Name of a Y-X-T speckle .dat file in SaveFolder.
%                    Arrays, other extensions, and other layouts are not
%                    supported.
%
%   Name-Value parameters:
%       'bNormalize' - Logical scalar. Normalize the finished flow map by its
%                      per-pixel temporal mean. Default: false
%
%   Output:
%       outData    - Full path of the Y-X-T Flow.dat output in SaveFolder
%                    (single precision, same axes, rate, and exposure as the
%                    input).
%
%   Notes:
%       - The file is read, processed, and written in chunks by
%         Ana_Speckle (Low-RAM mode is always on).
%       - The layout is checked first, so a refused input writes nothing.

% Default output for pipeline management.
default_Output = 'Flow.dat';

if nargin == 1 && (ischar(SaveFolder) || (isstring(SaveFolder) && isscalar(SaveFolder))) && ...
        strcmpi(strtrim(char(string(SaveFolder))), 'pipelineInfo')
    outData = localPipelineInfo();
    return
end

p = inputParser;
p.FunctionName = 'run_Ana_Speckle';
addRequired(p, 'SaveFolder', @(x) (ischar(x) || (isstring(x) && isscalar(x))) && isfolder(x));
addRequired(p, 'data');
addParameter(p, 'bNormalize', false, @(x) islogical(x) && isscalar(x));
parse(p, SaveFolder, data, varargin{:});

SaveFolder = char(string(p.Results.SaveFolder));
bNormalize = p.Results.bNormalize;

assert(ischar(data) || (isstring(data) && isscalar(data)), ...
    'Umitoolbox:run_Ana_Speckle:UnsupportedInputType', ...
    'Input "data" must be the name of a Y-X-T .dat file (arrays are not supported).');

speckleFile = char(string(data));
[~, speckleBase, speckleExt] = fileparts(speckleFile);
assert(isempty(speckleExt) || strcmpi(speckleExt, '.dat'), ...
    'Umitoolbox:run_Ana_Speckle:UnsupportedInputFile', ...
    'Unsupported input file extension "%s". Only .dat files are supported.', speckleExt);

datFile = fullfile(SaveFolder, [speckleBase '.dat']);
assert(isfile(datFile), ...
    'Umitoolbox:run_Ana_Speckle:FileNotFound', ...
    'Speckle .dat file not found: "%s".', datFile);
assertDatLayout(loadMetaData(datFile), {{'Y','X','T'}}, 'run_Ana_Speckle');

fprintf('Calculating blood flow...\n');

outData = Ana_Speckle( ...
    SaveFolder, ...
    bNormalize, ...
    'Filename', speckleBase, ...
    'RAMSafeMode', true);

fprintf('Finished Ana_Speckle.\n');

    function info = localPipelineInfo()
        info = PipelineManager.createPipelineInfo( ...
            'run_Ana_Speckle', ...
            'Wrapper around Ana_Speckle for blood-flow computation from speckle data.');
        info.version = '2.0.0';

        info = PipelineManager.addInput(info, ...
            'SaveFolder', ...
            'SaveFolder', ...
            'Folder containing the speckle input and metadata.', ...
            'kind', 'input', ...
            'position', 1, ...
            'callType', 'positional', ...
            'isData', false);

        info = PipelineManager.addInput(info, ...
            'data', ...
            'ImageTimeSeries', ...
            'Y-X-T speckle .dat file.', ...
            'position', 2, ...
            'callType', 'positional', ...
            'isData', true, ...
            'supportsFile', true, ...
            'dataMode', 'file');

        info = PipelineManager.addInput(info, ...
            'bNormalize', ...
            'parameter', ...
            'If true, normalize each frame by the temporal mean.', ...
            'kind', 'parameter', ...
            'position', 3, ...
            'callType', 'namevalue', ...
            'default', false, ...
            'allowed', [true false], ...
            'dataType', 'logical');

        info = PipelineManager.addOutput(info, ...
            'outData', ...
            {'ImageTimeSeries', 'ProcessedData'}, ...
            'data', ...
            'Blood-flow output from Ana_Speckle: a single Y-X-T .dat image time series.', ...
            default_Output, ...
            1, ...
            'isData', true, ...
            'saveFileName', default_Output);
    end
end
