function varargout = run_HemoCompute(SaveFolder, data, varargin)
%RUN_HEMOCOMPUTE Wrapper around HemoCompute.
%
%   outFile = run_HemoCompute(SaveFolder, data)
%   [HbOFile, HbRFile] = run_HemoCompute(SaveFolder, data)
%   outFile = run_HemoCompute(SaveFolder, data, 'FilterSet', 'none', ...)
%   run_HemoCompute('preflight', SaveFolder, parameters)
%
%   This wrapper normalizes stable canonical illumination names, resolves
%   acquisition/Rig optical information, and dispatches HemoCompute in
%   standard or RAM-safe mode depending on the type of "data". Channel
%   timebase differences are resolved inside HemoCompute from AcqInfos.mat.
%   If AcqInfos does not identify a Rig, the existing active default Rig is
%   used with a warning; the acquisition metadata is not modified.
%
%   Inputs:
%       SaveFolder - Folder containing AcqInfos.mat and intrinsic channels.
%       data       - Numeric YXT array or raw .dat filename.
%
%   Name-Value parameters:
%       'FilterSet'              - Filter set name.
%       'b_normalize'            - Whether to normalize input channels.
%       'Illuminations'          - Two or three canonical names from
%                                  {'red','green','yellow'}. Historical
%                                  alias 'amber' is normalized to 'yellow'.
%       'HbT_concentration_uM'   - Total hemoglobin concentration.
%       'StO2perc'               - Oxygen saturation percentage.
%
%   Outputs:
%       outFile           - With one requested output, returns
%                           {HbOFile,HbRFile} for legacy callers.
%       HbOFile, HbRFile  - With two requested outputs, returns the two
%                           files separately for PipelineManager.

% Default outputs for pipeline management.
default_Output = {'HbO.dat', 'HbR.dat'}; 

if nargin == 1 && (ischar(SaveFolder) || (isstring(SaveFolder) && isscalar(SaveFolder))) && ...
        strcmpi(strtrim(char(string(SaveFolder))), 'pipelineInfo')
    varargout{1} = localPipelineInfo();
    return
end

if nargin >= 1 && (ischar(SaveFolder) || (isstring(SaveFolder) && isscalar(SaveFolder))) && ...
        strcmpi(strtrim(char(string(SaveFolder))), 'preflight')
    if nargin ~= 3 || numel(varargin) ~= 1
        error('Umitoolbox:run_HemoCompute:InvalidPreflightCall', ...
            'Use run_HemoCompute(''preflight'', SaveFolder, parameters).');
    end
    localPreflight(data, varargin{1});
    if nargout > 0
        varargout = cell(1, nargout);
    end
    return
end

p = inputParser;
p.FunctionName = 'run_HemoCompute';
addRequired(p, 'SaveFolder', @(x) (ischar(x) || (isstring(x) && isscalar(x))) && isfolder(x));
addRequired(p, 'data', @(x) (isnumeric(x) && ndims(x) == 3) || ischar(x) || (isstring(x) && isscalar(x)));
addParameter(p, 'FilterSet', 'none', @(x) ischar(x) || (isstring(x) && isscalar(x)));
addParameter(p, 'b_normalize', true, @(x) islogical(x) && isscalar(x));
addParameter(p, 'Illuminations', {'red','green','yellow'}, ...
    @(x) (iscell(x) && (isempty(x) || isvector(x))) || ...
    (isstring(x) && (isempty(x) || isvector(x))));
addParameter(p, 'HbT_concentration_uM', 100, @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x > 0);
addParameter(p, 'StO2perc', 60, @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x > 0 && x <= 100);
parse(p, SaveFolder, data, varargin{:});

SaveFolder = char(string(p.Results.SaveFolder));
filterSet = char(string(p.Results.FilterSet));
b_normalize = p.Results.b_normalize;
illuminationInput = cellstr(string(p.Results.Illuminations));
HbT_uM = double(p.Results.HbT_concentration_uM);
O2_sat = double(p.Results.StO2perc);

illumination = cellfun(@UMITRigStore.normalizeIlluminationName, ...
    illuminationInput, 'UniformOutput', false);

assert(numel(illumination) >= 2, ...
    'Umitoolbox:run_HemoCompute:InvalidInput', ...
    'At least two different illumination wavelengths must be selected.');

% Decide RAM-safe mode from input type.
b_lowRAMmode = ischar(data) || (isstring(data) && isscalar(data));
opticalInfo = localResolveOpticalInfo(SaveFolder, illumination, filterSet);

try
    [HbO, HbR] = HemoCompute( ...
        SaveFolder, ...
        SaveFolder, ...
        filterSet, ...
        illumination, ...
        b_normalize, ...
        'HbT_uM', HbT_uM, ...
        'O2_sat', O2_sat, ...
        'OpticalInfo', opticalInfo, ...
        'RAMSafeMode', b_lowRAMmode);
catch ME
    ME = addCause(ME, MException( ...
        'Umitoolbox:run_HemoCompute:UnknownError', ...
        'Function HemoCompute failed.'));
    throw(ME)
end

if nargout <= 1
    if b_lowRAMmode
        varargout{1} = {HbO, HbR};
    else
        varargout{1} = default_Output;
    end
elseif nargout == 2
    varargout = {HbO, HbR};
else
    error('Umitoolbox:run_HemoCompute:TooManyOutputs', ...
        'run_HemoCompute supports at most two outputs.');
end

fprintf('Finished HemoCompute.\n');

    function info = localPipelineInfo()
        info = PipelineManager.createPipelineInfo( ...
            'run_HemoCompute', ...
            'Wrapper around HemoCompute for HbO/HbR computation.');

        info = PipelineManager.addInput(info, ...
            'SaveFolder', ...
            'SaveFolder', ...
            'Folder containing AcqInfos.mat and intrinsic channels.', ...
            'kind', 'input', ...
            'position', 1, ...
            'callType', 'positional', ...
            'isData', false);

        info = PipelineManager.addInput(info, ...
            'data', ...
            'ImageTimeSeries', ...
            'Numeric YXT input or raw .dat filename.', ...
            'position', 2, ...
            'callType', 'positional', ...
            'isData', true, ...
            'supportsFile', true, ...
            'dataMode', 'either');

        info = PipelineManager.addInput(info, ...
            'FilterSet', ...
            'parameter', ...
            'Intrinsic imaging filter set.', ...
            'kind', 'parameter', ...
            'position', 3, ...
            'callType', 'namevalue', ...
            'default', 'none', ...
            'allowed', {'gCaMP','jrGECO','none'}, ...
            'dataType', 'char');

        info = PipelineManager.addInput(info, ...
            'b_normalize', ...
            'parameter', ...
            'Whether to normalize channels before computation.', ...
            'kind', 'parameter', ...
            'position', 4, ...
            'callType', 'namevalue', ...
            'default', true, ...
            'allowed', {false,true}, ...
            'dataType', 'logical');

        info = PipelineManager.addInput(info, ...
            'Illuminations', ...
            'parameter', ...
            ['Canonical semantic illumination names. Stored values stay stable ' ...
            'when Rig display names or physical spectrum IDs change.'], ...
            'kind', 'parameter', ...
            'position', 5, ...
            'callType', 'namevalue', ...
            'default', {'red','green','yellow'}, ...
            'allowed', {'red';'green';'yellow'}, ...
            'dataType', 'char');

        info = PipelineManager.addInput(info, ...
            'HbT_concentration_uM', ...
            'parameter', ...
            'Total hemoglobin concentration in micromolar.', ...
            'kind', 'parameter', ...
            'position', 6, ...
            'callType', 'namevalue', ...
            'default', 100, ...
            'dataType', 'numeric');

        info = PipelineManager.addInput(info, ...
            'StO2perc', ...
            'parameter', ...
            'Oxygen saturation percentage.', ...
            'kind', 'parameter', ...
            'position', 7, ...
            'callType', 'namevalue', ...
            'default', 60, ...
            'dataType', 'numeric');

        info = PipelineManager.addOutput(info, ...
            'HbO', ...
            'ImageTimeSeries', ...
            'data', ...
            'Oxygenated hemoglobin data or RAM-safe backing file.', ...
            default_Output{1}, ...
            1, ...
            'isData', true);

        info = PipelineManager.addOutput(info, ...
            'HbR', ...
            'ImageTimeSeries', ...
            'data', ...
            'Deoxygenated hemoglobin data or RAM-safe backing file.', ...
            default_Output{2}, ...
            2, ...
            'isData', true);

        info.supportsPreflight = true;
    end
end

function localPreflight(saveFolder, parameters)
%LOCALPREFLIGHT Validate Rig optics before pipeline execution.

if ~isstruct(parameters)
    error('Umitoolbox:run_HemoCompute:InvalidPreflightParameters', ...
        'Pipeline preflight parameters must be a struct array.');
end
names = {parameters.name};
illuminationIdx = find(strcmpi(names, 'Illuminations'), 1);
filterSetIdx = find(strcmpi(names, 'FilterSet'), 1);
if isempty(illuminationIdx) || isempty(filterSetIdx)
    error('Umitoolbox:run_HemoCompute:InvalidPreflightParameters', ...
        'HemoCompute preflight requires Illuminations and FilterSet parameters.');
end
localResolveOpticalInfo( ...
    saveFolder, parameters(illuminationIdx).value, parameters(filterSetIdx).value);
end

function [opticalInfo, acqInfo, rigStore] = localResolveOpticalInfo( ...
        saveFolder, illuminations, filterSet)
%LOCALRESOLVEOPTICALINFO Resolve dataset, Rig, and filter-set optics.

saveFolder = char(string(saveFolder));
acqFile = fullfile(saveFolder, 'AcqInfos.mat');
if ~isfile(acqFile)
    error('Umitoolbox:HemoCompute:MissingAcqInfos', ...
        'AcqInfos.mat was not found in "%s".', saveFolder);
end
loaded = load(acqFile, 'AcqInfoStream');
if ~isfield(loaded, 'AcqInfoStream') || ...
        ~isstruct(loaded.AcqInfoStream) || ~isscalar(loaded.AcqInfoStream)
    error('Umitoolbox:HemoCompute:InvalidAcqInfos', ...
        'AcqInfos.mat does not contain a scalar AcqInfoStream structure.');
end
acqInfo = loaded.AcqInfoStream;

if isfield(acqInfo, 'rigUUID') && ~isempty(acqInfo.rigUUID)
    rigStore = UMITRigStore.open(acqInfo.rigUUID);
elseif isfield(acqInfo, 'rigID') && ~isempty(acqInfo.rigID)
    rigStore = UMITRigStore.openByRigID(acqInfo.rigID);
else
    rigStore = localResolveActiveRig();
    rigInfo = rigStore.getRigInfo();
    warning('Umitoolbox:HemoCompute:MissingRigUsingActiveRig', ...
        ['AcqInfoStream does not identify a Rig. Using active Rig "%s" ' ...
        'for HemoCompute without modifying AcqInfos.mat.'], rigInfo.rigID);
end

opticalInfo = rigStore.resolveOpticalConfiguration( ...
    acqInfo, illuminations, filterSet, saveFolder);
end

function rigStore = localResolveActiveRig()
%LOCALRESOLVEACTIVERIG Resolve an existing active Rig without creating one.

rigStore = UMITRigStore.getDefaultRig();
if ~isempty(rigStore)
    return
end

rigs = UMITRigStore.listRigs();
candidates = rigs(rigs.Status == "active" & rigs.IsReadable, :);
if height(candidates) == 1
    rigStore = UMITRigStore.open(char(candidates.RigUUID(1)));
    return
end

if isempty(candidates)
    detail = 'No active readable Rig exists.';
else
    detail = 'Multiple active Rigs exist and none is selected as default.';
end
error('Umitoolbox:HemoCompute:MissingRig', ...
    ['AcqInfoStream does not identify a Rig. %s Select an active default ' ...
    'Rig before running HemoCompute.'], detail);
end
