function outFile = run_HemoCompute(SaveFolder, data, varargin)
%RUN_HEMOCOMPUTE Wrapper around HemoCompute.
%
%   outFile = run_HemoCompute(SaveFolder, data)
%   outFile = run_HemoCompute(SaveFolder, data, 'FilterSet', 'none', ...)
%
%   This wrapper translates user-facing channel selection flags into the
%   illumination list expected by HemoCompute and dispatches the call in
%   standard or RAM-safe mode depending on the type of "data".
%
%   Inputs:
%       SaveFolder - Folder containing AcqInfos.mat and intrinsic channels.
%       data       - Numeric YXT array or raw .dat filename.
%
%   Name-Value parameters:
%       'FilterSet'              - Filter set name.
%       'b_normalize'            - Whether to normalize input channels.
%       'Red'                    - Use red illumination.
%       'Green'                  - Use green illumination.
%       'Amber'                  - Use amber/yellow illumination.
%       'HbT_concentration_uM'   - Total hemoglobin concentration.
%       'StO2perc'               - Oxygen saturation percentage.
%
%   Output:
%       outFile - {'HbO.dat','HbR.dat'} or the corresponding
%                 '_preallocData' names when RAM-safe mode uses file
%                 preallocation fallbacks.

% Default outputs for pipeline management.
default_Output = {'HbO.dat', 'HbR.dat'}; %#ok<NASGU>

if nargin == 1 && (ischar(SaveFolder) || (isstring(SaveFolder) && isscalar(SaveFolder))) && ...
        strcmpi(strtrim(char(string(SaveFolder))), 'pipelineInfo')
    outFile = localPipelineInfo();
    return
end

p = inputParser;
p.FunctionName = 'run_HemoCompute';
addRequired(p, 'SaveFolder', @(x) (ischar(x) || (isstring(x) && isscalar(x))) && isfolder(x));
addRequired(p, 'data', @(x) (isnumeric(x) && ndims(x) == 3) || ischar(x) || (isstring(x) && isscalar(x)));
addParameter(p, 'FilterSet', 'none', @(x) ischar(x) || (isstring(x) && isscalar(x)));
addParameter(p, 'b_normalize', true, @(x) islogical(x) && isscalar(x));
addParameter(p, 'Red', true, @(x) islogical(x) && isscalar(x));
addParameter(p, 'Green', true, @(x) islogical(x) && isscalar(x));
addParameter(p, 'Amber', true, @(x) islogical(x) && isscalar(x));
addParameter(p, 'HbT_concentration_uM', 100, @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x > 0);
addParameter(p, 'StO2perc', 60, @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x > 0 && x <= 100);
parse(p, SaveFolder, data, varargin{:});

SaveFolder = char(string(p.Results.SaveFolder));
filterSet = char(string(p.Results.FilterSet));
b_normalize = p.Results.b_normalize;
useRed = p.Results.Red;
useGreen = p.Results.Green;
useAmber = p.Results.Amber;
HbT_uM = double(p.Results.HbT_concentration_uM);
O2_sat = double(p.Results.StO2perc);

% Translate wrapper options to illumination list.
illumination = {};
if useRed
    illumination{end+1} = 'red'; %#ok<AGROW>
end
if useGreen
    illumination{end+1} = 'green'; %#ok<AGROW>
end
if useAmber
    illumination{end+1} = 'amber'; %#ok<AGROW>
end

assert(~isempty(illumination), ...
    'Umitoolbox:run_HemoCompute:InvalidInput', ...
    'At least one illumination must be selected.');

% Decide RAM-safe mode from input type.
b_lowRAMmode = ischar(data) || (isstring(data) && isscalar(data));

try
    [HbO, HbR] = HemoCompute( ...
        SaveFolder, ...
        SaveFolder, ...
        filterSet, ...
        illumination, ...
        b_normalize, ...
        'HbT_uM', HbT_uM, ...
        'O2_sat', O2_sat, ...
        'RAMSafeMode', b_lowRAMmode);
catch ME
    ME = addCause(ME, MException( ...
        'Umitoolbox:run_HemoCompute:UnknownError', ...
        'Function HemoCompute failed.'));
    throw(ME)
end

if b_lowRAMmode
    outFile = {HbO, HbR};
else
    outFile = default_Output;
end

fprintf('Finished HemoCompute.\n');

    function info = localPipelineInfo()
        info = PipelineManager.createPipelineInfo( ...
            'run_HemoCompute', ...
            'Wrapper around HemoCompute for HbO/HbR computation.');

        info = PipelineManager.addInput(info, ...
            'SaveFolder', ...
            {'parameter'}, ...
            'Folder containing AcqInfos.mat and intrinsic channels.', ...
            'kind', 'parameter', ...
            'position', 1, ...
            'callType', 'positional', ...
            'default', '', ...
            'dataType', 'char');

        info = PipelineManager.addInput(info, ...
            'data', ...
            'ImageTimeSeries', ...
            'Numeric YXT input or raw .dat filename.', ...
            'position', 2, ...
            'callType', 'positional', ...
            'isData', true, ...
            'supportsFile', true, ...
            'dataMode', 'either');

        info = PipelineManager.addInput(info, ...
            'FilterSet', ...
            'parameter', ...
            'Intrinsic imaging filter set.', ...
            'kind', 'parameter', ...
            'position', 3, ...
            'callType', 'namevalue', ...
            'default', 'none', ...
            'allowed', {'gCaMP','jrGECO','none'}, ...
            'dataType', 'char');

        info = PipelineManager.addInput(info, ...
            'b_normalize', ...
            'parameter', ...
            'Whether to normalize channels before computation.', ...
            'kind', 'parameter', ...
            'position', 4, ...
            'callType', 'namevalue', ...
            'default', true, ...
            'allowed', {false,true}, ...
            'dataType', 'logical');

        info = PipelineManager.addInput(info, ...
            'Red', ...
            'parameter', ...
            'Use red illumination.', ...
            'kind', 'parameter', ...
            'position', 5, ...
            'callType', 'namevalue', ...
            'default', true, ...
            'allowed', {false,true}, ...
            'dataType', 'logical');

        info = PipelineManager.addInput(info, ...
            'Green', ...
            'parameter', ...
            'Use green illumination.', ...
            'kind', 'parameter', ...
            'position', 6, ...
            'callType', 'namevalue', ...
            'default', true, ...
            'allowed', {false,true}, ...
            'dataType', 'logical');

        info = PipelineManager.addInput(info, ...
            'Amber', ...
            'parameter', ...
            'Use amber/yellow illumination.', ...
            'kind', 'parameter', ...
            'position', 7, ...
            'callType', 'namevalue', ...
            'default', true, ...
            'allowed', {false,true}, ...
            'dataType', 'logical');

        info = PipelineManager.addInput(info, ...
            'HbT_concentration_uM', ...
            'parameter', ...
            'Total hemoglobin concentration in micromolar.', ...
            'kind', 'parameter', ...
            'position', 8, ...
            'callType', 'namevalue', ...
            'default', 100, ...
            'dataType', 'numeric');

        info = PipelineManager.addInput(info, ...
            'StO2perc', ...
            'parameter', ...
            'Oxygen saturation percentage.', ...
            'kind', 'parameter', ...
            'position', 9, ...
            'callType', 'namevalue', ...
            'default', 60, ...
            'dataType', 'numeric');

        info = PipelineManager.addOutput(info, ...
            'HbO', ...
            'ImageTimeSeries', ...
            'data', ...
            'Oxygenated hemoglobin output.', ...
            default_Output{1}, ...
            1, ...
            'isData', true);

        info = PipelineManager.addOutput(info, ...
            'HbR', ...
            'ImageTimeSeries', ...
            'data', ...
            'Deoxygenated hemoglobin output.', ...
            default_Output{2}, ...
            2, ...
            'isData', true);
    end
end
