function outData = run_Ana_Speckle(SaveFolder, data, varargin)
%RUN_ANA_SPECKLE Wrapper around Ana_Speckle (blood flow from speckle data).
%
%   outData = run_Ana_Speckle(SaveFolder, data)
%   outData = run_Ana_Speckle(SaveFolder, data, 'bNormalize', true)
%   outData = run_Ana_Speckle(SaveFolder, array, 'FrameRateHz', 10, 'ExposureMsec', 5)
%
%   This wrapper runs Ana_Speckle. The nature of "data" selects the mode.
%
%   Inputs:
%       SaveFolder - Existing folder. Resolves a bare .dat file name and
%                    receives the Flow.dat output.
%       data       - The speckle data, in one of two forms:
%                      * Name or path of a Y-X-T .dat file (a bare name,
%                        with or without ".dat", is looked up in SaveFolder).
%                        The file is read, processed, and written in chunks
%                        (Low-RAM mode).
%                      * Numeric Y-X-T array with at least 2 frames. It is
%                        processed in RAM (Standard mode).
%                    Other extensions, other layouts, UMT structs, and .umt
%                    files are not supported.
%
%   Name-Value parameters:
%       'bNormalize'   - Logical scalar. Normalize the finished flow map by
%                        its per-pixel temporal mean. Default: false
%       'FrameRateHz'  - Frame rate of the data (Hz). PipelineManager injects
%                        it from the data; a .dat file's header provides it
%                        otherwise. An array needs it explicitly.
%       'ExposureMsec' - Speckle exposure time (ms), with the same rules as
%                        'FrameRateHz'. AcqInfos.mat is not used.
%
%   Output:
%       outData    - File input: full path of the Y-X-T Flow.dat output in
%                    SaveFolder (single precision, same axes, rate, and
%                    exposure as the input).
%                    Array input: single-precision Y-X-T flow array.
%
%   Notes:
%       - The layout of a file is checked first, so a refused input writes
%         nothing.

% Default output for pipeline management.
default_Output = 'Flow.dat';

if nargin == 1 && (ischar(SaveFolder) || (isstring(SaveFolder) && isscalar(SaveFolder))) && ...
        strcmpi(strtrim(char(string(SaveFolder))), 'pipelineInfo')
    outData = localPipelineInfo();
    return
end

p = inputParser;
p.FunctionName = 'run_Ana_Speckle';
addRequired(p, 'SaveFolder', @(x) (ischar(x) || (isstring(x) && isscalar(x))) && isfolder(x));
addRequired(p, 'data');
addParameter(p, 'bNormalize', false, @(x) islogical(x) && isscalar(x));
addParameter(p, 'FrameRateHz', []);
addParameter(p, 'ExposureMsec', []);
parse(p, SaveFolder, data, varargin{:});

SaveFolder = char(string(p.Results.SaveFolder));
bNormalize = p.Results.bNormalize;

% Only forward the metadata that was given: Ana_Speckle applies the
% explicit > header > error precedence.
metaArgs = {};
if ~isempty(p.Results.FrameRateHz)
    metaArgs = [metaArgs, {'FrameRateHz', p.Results.FrameRateHz}];
end
if ~isempty(p.Results.ExposureMsec)
    metaArgs = [metaArgs, {'ExposureMsec', p.Results.ExposureMsec}];
end

% -------------------------------------------------------------------------
% Resolve and validate the input. The type of "data" selects the mode.
% -------------------------------------------------------------------------
if ischar(data) || (isstring(data) && isscalar(data))
    % Filename: Low-RAM mode.
    [dataFolder, dataStem, dataExt] = fileparts(char(string(data)));
    assert(isempty(dataExt) || strcmpi(dataExt, '.dat'), ...
        'Umitoolbox:run_Ana_Speckle:UnsupportedInputFile', ...
        'Unsupported input file extension "%s". Only .dat files are supported.', dataExt);

    % A bare name is looked up in SaveFolder; a path is used as given.
    if isempty(dataFolder)
        datFile = fullfile(SaveFolder, [dataStem '.dat']);
    else
        datFile = fullfile(dataFolder, [dataStem '.dat']);
    end
    assert(isfile(datFile), ...
        'Umitoolbox:run_Ana_Speckle:FileNotFound', ...
        'Speckle .dat file not found: "%s".', datFile);
    assertDatLayout(loadMetaData(datFile), {{'Y','X','T'}}, 'run_Ana_Speckle');

    speckleInput = datFile;
    mode = 'Low-RAM';
elseif isnumeric(data) || islogical(data)
    % Array: Standard mode.
    assert(ndims(data) == 3 && ~isempty(data), ...
        'Umitoolbox:run_Ana_Speckle:unsupportedLayout', ...
        'Array input must be a non-empty Y x X x T array.');

    speckleInput = data;
    mode = 'Standard';
else
    error('Umitoolbox:run_Ana_Speckle:UnsupportedInputType', ...
        ['Input "data" must be the name of a Y-X-T .dat file or a numeric ' ...
         'Y-X-T array.']);
end

fprintf('Calculating blood flow (%s mode)...\n', mode);

outData = Ana_Speckle( ...
    speckleInput, ...
    SaveFolder, ...
    bNormalize, ...
    metaArgs{:});

fprintf('Finished Ana_Speckle.\n');

    function info = localPipelineInfo()
        info = PipelineManager.createPipelineInfo( ...
            'run_Ana_Speckle', ...
            'Wrapper around Ana_Speckle for blood-flow computation from speckle data.');
        info.version = '3.0.0';

        info = PipelineManager.addInput(info, ...
            'SaveFolder', ...
            'SaveFolder', ...
            'Folder resolving a bare file name and receiving Flow.dat.', ...
            'kind', 'input', ...
            'position', 1, ...
            'callType', 'positional', ...
            'isData', false);

        info = PipelineManager.addInput(info, ...
            'data', ...
            'ImageTimeSeries', ...
            'Y-X-T speckle data: a .dat file (Low-RAM mode) or a numeric array (Standard mode).', ...
            'position', 2, ...
            'callType', 'positional', ...
            'isData', true, ...
            'supportsFile', true, ...
            'dataMode', 'either');

        info = PipelineManager.addInput(info, ...
            'bNormalize', ...
            'parameter', ...
            'If true, normalize the finished flow map by its own temporal mean.', ...
            'kind', 'parameter', ...
            'position', 3, ...
            'callType', 'namevalue', ...
            'default', false, ...
            'allowed', [true false], ...
            'dataType', 'logical');

        info = PipelineManager.addInput(info, ...
            'FrameRateHz', ...
            'sourceInfo', ...
            'Frame rate of the input data (Hz), injected from the data.', ...
            'kind', 'sourceInfo', ...
            'sourceField', 'frameRateHz', ...
            'required', false);

        info = PipelineManager.addInput(info, ...
            'ExposureMsec', ...
            'sourceInfo', ...
            'Speckle exposure of the input data (ms), injected from the data.', ...
            'kind', 'sourceInfo', ...
            'sourceField', 'exposureMsec', ...
            'required', false);

        info = PipelineManager.addOutput(info, ...
            'outData', ...
            {'ImageTimeSeries', 'ProcessedData'}, ...
            'data', ...
            'Blood-flow output from Ana_Speckle: a single Y-X-T .dat image time series.', ...
            default_Output, ...
            1, ...
            'isData', true, ...
            'saveFileName', default_Output);
    end
end
