function outFile = genCorrelationMatrix(File,SaveFolder, varargin)
% GENCORRELATIONMATRIX creates a correlation matrix from SPCM data extracted using
% getDataFromROI function.

% Inputs:
% File (str) = fullpath of an ROI_xxxx.mat file containing Seed Pixel
% Correlation Data.
% SaveFolder(str) = fullpath of folder containing FILE and to save the
% correlation Matrix file.
% Output (str) = custom output filename (not implemented yet).

% Output:
% out (str) = name of .MAT file generated by this function.

% Defaults:
default_Output = 'CorrMatrix.mat'; 
%%% Arguments parsing and validation %%%
p = inputParser;
% The input of the function must be a File , RawFolder or SaveFolder
% Imaging Object:
addRequired(p, 'File', @(x) isfile(x) & endsWith(x,'.mat') & contains(x,'ROI_'))
addRequired(p, 'SaveFolder', @isfolder);
addOptional(p, 'Output', default_Output)
% Parse inputs:
parse(p,File, SaveFolder, varargin{:});
% Initialize Variables:
dataFile = matfile(p.Results.File);
SaveFolder = p.Results.SaveFolder;
% outFile = p.Results.Output;
%%%%
% Load ROI file:
ROIfile = load (dataFile.ROIfile);
% Select observations in ROIfile:
idx_obs = ismember({ROIfile.ROI_info.Name}, dataFile.obsID);
ROIfile.ROI_info(~idx_obs)= [];
% Find seed frames in ROIfile masks:
centroid_px = arrayfun(@(x) find(bwmorph(x.Stats.ROI_binary_mask,'shrink', Inf),...
    1, 'last'), ROIfile.ROI_info, 'UniformOutput', true);
if size(dataFile.obsID,1)~= size(centroid_px,1)
    centroid_px = centroid_px';
end
% Rearrange centroid_px to match dataFile.obsID list
[~,lb] = ismember({ROIfile.ROI_info.Name}, dataFile.obsID);
centroid_px = centroid_px(lb);
% Fill the correlation matrix with values:
corrMat = cellfun(@(x) single(x(centroid_px)),dataFile.data, 'UniformOutput',0);
% Create new dimension names as {'O', 'O'}:
dim_names = {'O','O'};
% Save to .MAT file and append dataFile variables to i:
[~,filename,ext] = fileparts(p.Results.File);
outFile = ['CorrMatrix_' filename ext];
save2Mat(fullfile(SaveFolder, outFile), corrMat,dataFile.obsID, dim_names, 'appendMetaData', dataFile);
end
