function outData = genImageTimeSeriesUMT(data, varargin)
%GENIMAGETIMESERIESUMT Package a numeric YXT array into a UMT structure.
%
%   outData = genImageTimeSeriesUMT(data)
%   outData = genImageTimeSeriesUMT(data, 'EntryName', 'main')
%   outData = genImageTimeSeriesUMT(data, 'EntryName', 'main', 'Labels', labels)
%
%   This function replaces the deprecated DATSTAT-style packaging workflow
%   with a direct UMT constructor for image time-series data.
%
%   Input:
%       data - Numeric or logical array with dimensions Y x X x T.
%
%   Name-Value parameters:
%       EntryName - Name of the created UMT entry. Default: 'main'
%       Labels    - Optional top-level labels struct. Default: struct()
%
%   Output:
%       outData   - UMT struct with kind = 'image' and dimNames {'Y','X','T'}.

% Default output for pipeline management.
default_Output = 'imageTimeSeries.umt'; %#ok<NASGU>

if nargin == 1 && (ischar(data) || (isstring(data) && isscalar(data))) && ...
        strcmpi(strtrim(char(string(data))), 'pipelineInfo')
    outData = localPipelineInfo();
    return
end

p = inputParser;
p.FunctionName = 'genImageTimeSeriesUMT';
addRequired(p, 'data', @(x) (isnumeric(x) || islogical(x)) && ndims(x) == 3);
addParameter(p, 'EntryName', 'main', @(x) ischar(x) || (isstring(x) && isscalar(x)));
addParameter(p, 'Labels', struct(), @(x) isstruct(x) && isscalar(x));
parse(p, data, varargin{:});

data = p.Results.data;
entryName = char(string(p.Results.EntryName));
labels = p.Results.Labels;

if isempty(fieldnames(labels))
    outData = genUMTStruct( ...
        data, ...
        'kind', 'image', ...
        'entryName', entryName, ...
        'dimNames', {'Y','X','T'});
else
    outData = genUMTStruct( ...
        data, ...
        'kind', 'image', ...
        'entryName', entryName, ...
        'dimNames', {'Y','X','T'}, ...
        'labels', labels);
end

validateUMTStruct(outData, 'requireEventInfo', true);

    function info = localPipelineInfo()
        info = PipelineManager.createPipelineInfo( ...
            'genImageTimeSeriesUMT', ...
            'Package a numeric YXT array into a UMT image time-series structure.');

        info = PipelineManager.addInput(info, ...
            'data', ...
            'ImageTimeSeries', ...
            'Numeric YXT input array.', ...
            'position', 1, ...
            'callType', 'positional', ...
            'isData', true, ...
            'supportsFile', false, ...
            'dataMode', 'ram');

        info = PipelineManager.addInput(info, ...
            'EntryName', ...
            'parameter', ...
            'Name of the created UMT entry.', ...
            'kind', 'parameter', ...
            'position', 2, ...
            'callType', 'namevalue', ...
            'default', 'main', ...
            'dataType', 'char');

        info = PipelineManager.addInput(info, ...
            'Labels', ...
            'parameter', ...
            'Optional top-level labels struct.', ...
            'kind', 'parameter', ...
            'position', 3, ...
            'callType', 'namevalue', ...
            'default', struct(), ...
            'dataType', 'struct');

        info = PipelineManager.addOutput(info, ...
            'outData', ...
            'ProcessedData', ...
            'data', ...
            'UMT-packaged image time-series output.', ...
            default_Output, ...
            1, ...
            'isData', true);
    end
end
