classdef TestSimplifyROIMaskPolygon < matlab.unittest.TestCase
    %TESTSIMPLIFYROIMASKPOLYGON Tests compact, topology-preserving ROI polygons.

    methods (Test)
        function reducesTypicalMaskBoundary(testCase)
            mask = false(180, 180);
            theta = linspace(0, 2 * pi, 721).';
            radius = 55 + 5 * sin(7 * theta) + 2 * sin(19 * theta);
            x = 90 + radius .* cos(theta);
            y = 90 + radius .* sin(theta);
            mask = poly2mask(x, y, size(mask, 1), size(mask, 2));

            [pgon, verticesXY, info] = simplifyROIMaskPolygon(mask);

            testCase.verifyClass(pgon, 'polyshape');
            testCase.verifyGreaterThanOrEqual(size(verticesXY, 1), 3);
            testCase.verifyEqual(info.tolerance, 0.01);
            testCase.verifyLessThan(info.nOutputVertices, 0.75 * info.nInputVertices);
            testCase.verifyLessThanOrEqual(info.pixelDifference, info.maxPixelDifference);
            testCase.verifyLessThanOrEqual(info.appliedTolerance, info.tolerance);
            testCase.verifyFalse(info.usedOriginalBoundaryFallback);
        end

        function preservesDisconnectedComponentsAndHole(testCase)
            mask = false(100, 120);
            mask(10:70, 10:80) = true;
            mask(28:50, 32:58) = false;
            mask(35:42, 40:48) = true;
            mask(75:90, 95:112) = true;

            [pgon, verticesXY, info] = simplifyROIMaskPolygon(mask);

            testCase.verifyEqual(numboundaries(pgon), 4);
            testCase.verifyEqual(info.nBoundaries, 4);
            testCase.verifyEqual(info.nHoles, 1);
            testCase.verifyTrue(all(isfinite(verticesXY), 'all'));

            roi = iMakeROI(pgon, verticesXY, mask);
            roiFile = createROIFile(size(mask), 'ROIs', roi);
            testCase.verifyWarningFree(@() validateROIFile(roiFile));
        end

        function rejectsEmptyMasks(testCase)
            testCase.verifyError(@() simplifyROIMaskPolygon(false(10, 10)), ...
                'simplifyROIMaskPolygon:EmptyMask');
        end
    end
end

function roi = iMakeROI(pgon, verticesXY, mask)
%IMAKEROI Build the minimum valid ROI schema entry for validation coverage.

stats = struct( ...
    'computedOn', datetime('now'), ...
    'NPixels', nnz(mask), ...
    'areaPx2', nnz(mask), ...
    'areaMM2', [], ...
    'centroidXY_px', [], ...
    'centroidXY_mm', [], ...
    'distanceFromOrigin_px', [], ...
    'distanceFromOrigin_mm', [], ...
    'spatialMean', [], ...
    'spatialStd', [], ...
    'spatialMedian', [], ...
    'spatialMin', [], ...
    'spatialMax', []);

roi = struct( ...
    'name', 'TopologyPreservingROI', ...
    'type', 'polygon', ...
    'DOC', datetime('now'), ...
    'modifiedOn', datetime('now'), ...
    'color', [1 0 0], ...
    'notes', '', ...
    'geometry', struct( ...
        'polyshape', pgon, ...
        'verticesXY_px', verticesXY, ...
        'ROIType', 'polygon', ...
        'ROIParameters', struct('ROIType', 'polygon', ...
            'Position', verticesXY, 'Vertices', verticesXY)), ...
    'mask', logical(mask), ...
    'stats', stats);

end
