function [outData, roiFile] = genVSM(retinotopyUMT, SaveFolder, varargin)
%GENVSM Generate a Visual Sign Map from retinotopy-map UMT input.
%
%   [outData, roiFile] = genVSM(retinotopyUMT, SaveFolder)
%   [outData, roiFile] = genVSM(retinotopyUMT, SaveFolder, 'Name', Value, ...)
%
%   This function creates a Visual Sign Map (VSM) from the phase
%   components of the Azimuth and Elevation maps produced by
%   genRetinotopyMaps.
%
%   Inputs:
%       retinotopyUMT - UMT struct output from genRetinotopyMaps.
%                       It must contain entries named:
%                           * AzimuthMap
%                           * ElevationMap
%                       and each entry must use dimNames {'Y','X','F'} with
%                       F = 2, where slice 1 is amplitude and slice 2 is phase.
%
%       SaveFolder    - Folder where the visual-area ROI file is saved.
%
%   Name-Value parameters:
%       PhaseMapFilter_Sigma - Gaussian sigma for phase-map smoothing.
%                              Default: 0
%       VSMFilter_Sigma      - Gaussian sigma for VSM smoothing.
%                              Default: 0
%       ROIFileName          - Output UMIT ROI filename.
%                              Default: 'VisualCtxAreas.roi'
%       b_UseMask            - If true, use a logical mask file during
%                              patch generation. Default: false
%       MaskFile             - Mask filename used when b_UseMask is true.
%                              Default: 'ImagingReferenceFrame.mat'
%                              A bare filename is resolved inside SaveFolder.
%
%   Output:
%       outData - UMT struct containing one image entry named VSM with
%                 dimNames {'Y','X'}.
%       roiFile - Folder-relative UMIT ROI filename. Empty when the
%                 segmentation finds no visual-area patches.
%
%   Notes:
%       - The output is derived exclusively from the retinotopy UMT input.
%       - Each connected patch is saved as CtxArea_<index>.

% Default output for pipeline management.
default_Output = 'visualSignMap.umt';

if nargin == 1 && (ischar(retinotopyUMT) || (isstring(retinotopyUMT) && isscalar(retinotopyUMT))) && ...
        strcmpi(strtrim(char(string(retinotopyUMT))), 'pipelineInfo')
    outData = localPipelineInfo();
    roiFile = [];
    return
end

p = inputParser;
p.FunctionName = 'genVSM';
addRequired(p, 'retinotopyUMT', @(x) isstruct(x) && isscalar(x));
addRequired(p, 'SaveFolder', @(x) (ischar(x) || (isstring(x) && isscalar(x))) && isfolder(x));
addParameter(p, 'PhaseMapFilter_Sigma', 0, @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x >= 0);
addParameter(p, 'VSMFilter_Sigma', 0, @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x >= 0);
addParameter(p, 'ROIFileName', 'VisualCtxAreas.roi', @(x) ischar(x) || (isstring(x) && isscalar(x)));
addParameter(p, 'b_UseMask', false, @(x) islogical(x) && isscalar(x));
addParameter(p, 'MaskFile', 'ImagingReferenceFrame.mat', @(x) ischar(x) || (isstring(x) && isscalar(x)));
parse(p, retinotopyUMT, SaveFolder, varargin{:});

opts = struct();
opts.PhaseMapFilter_Sigma = double(p.Results.PhaseMapFilter_Sigma);
opts.VSMFilter_Sigma = double(p.Results.VSMFilter_Sigma);
opts.ROIFileName = iNormalizeROIFileName(p.Results.ROIFileName);
opts.b_UseMask = p.Results.b_UseMask;
opts.MaskFile = char(string(p.Results.MaskFile));
SaveFolder = char(string(p.Results.SaveFolder));

validateUMTStruct(retinotopyUMT, 'requireEventInfo', false);
assert(strcmpi(retinotopyUMT.kind, 'image'), ...
    'Umitoolbox:genVSM:InvalidInput', ...
    'Input UMT must have kind = "image".');

requiredEntries = {'AzimuthMap', 'ElevationMap'};
for iEntry = 1:numel(requiredEntries)
    assert(isfield(retinotopyUMT.data, requiredEntries{iEntry}), ...
        'Umitoolbox:genVSM:MissingInput', ...
        'The retinotopy UMT must contain entry "%s".', requiredEntries{iEntry});

    thisEntry = retinotopyUMT.data.(requiredEntries{iEntry});
    thisDims = cellstr(string(thisEntry.dimNames));
    assert(isequal(thisDims, {'Y','X','F'}), ...
        'Umitoolbox:genVSM:InvalidInput', ...
        'Entry "%s" must use dimNames {''Y'',''X'',''F''}.', requiredEntries{iEntry});
    assert(size(thisEntry.value, 3) == 2, ...
        'Umitoolbox:genVSM:InvalidInput', ...
        'Entry "%s" must have F = 2 (Amplitude, Phase).', requiredEntries{iEntry});
end

azMap = single(retinotopyUMT.data.AzimuthMap.value);
elMap = single(retinotopyUMT.data.ElevationMap.value);

% Calculate Visual Sign Map from phase components.
phaseAz = azMap(:,:,2);
phaseEl = elMap(:,:,2);

phaseAz(isnan(phaseAz)) = 1000;
phaseEl(isnan(phaseEl)) = 1000;

if opts.PhaseMapFilter_Sigma > 0
    disp('Filtering phase maps...')
    phaseAz = imgaussfilt(phaseAz, opts.PhaseMapFilter_Sigma);
    phaseEl = imgaussfilt(phaseEl, opts.PhaseMapFilter_Sigma);
end

disp('Calculating visual sign map...');
[gradAzx, gradAzy] = gradient(phaseAz);
[gradElx, gradEly] = gradient(phaseEl);
gradDirAz = atan2(gradAzy, gradAzx);
gradDirEl = atan2(gradEly, gradElx);

vsm = sin(angle(exp(1i .* gradDirAz) .* exp(-1i .* gradDirEl)));
vsm(isnan(vsm)) = 0;

if opts.VSMFilter_Sigma > 0
    disp('Filtering visual sign map...')
    vsm = imgaussfilt(vsm, opts.VSMFilter_Sigma);
end

outData = genUMTStruct( ...
    single(vsm), ...
    'kind', 'image', ...
    'entryName', 'VSM', ...
    'dimNames', {'Y','X'});

disp('Finished creating VSM');

roiFile = genVAmask(vsm, size(vsm), SaveFolder, opts);

    function info = localPipelineInfo()
        info = PipelineManager.createPipelineInfo( ...
            'genVSM', ...
            'Generate a Visual Sign Map from retinotopy-map UMT input.');

        info = PipelineManager.addInput(info, ...
            'retinotopyUMT', ...
            'ProcessedData', ...
            'Retinotopy UMT containing AzimuthMap and ElevationMap entries.', ...
            'position', 1, ...
            'callType', 'positional', ...
            'isData', true, ...
            'supportsFile', false, ...
            'dataMode', 'ram');

        info = PipelineManager.addInput(info, ...
            'SaveFolder', ...
            'SaveFolder', ...
            'Folder where the visual-area ROI file is saved.', ...
            'kind', 'input', ...
            'position', 2, ...
            'callType', 'positional', ...
            'isData', false);

        info = PipelineManager.addInput(info, ...
            'PhaseMapFilter_Sigma', ...
            'parameter', ...
            'Gaussian sigma for phase-map smoothing.', ...
            'kind', 'parameter', ...
            'position', 3, ...
            'callType', 'namevalue', ...
            'default', 0, ...
            'allowed', [0 Inf], ...
            'dataType', 'numeric');

        info = PipelineManager.addInput(info, ...
            'VSMFilter_Sigma', ...
            'parameter', ...
            'Gaussian sigma for VSM smoothing.', ...
            'kind', 'parameter', ...
            'position', 4, ...
            'callType', 'namevalue', ...
            'default', 0, ...
            'allowed', [0 Inf], ...
            'dataType', 'numeric');

        info = PipelineManager.addInput(info, ...
            'ROIFileName', ...
            'parameter', ...
            'Output filename for visual-area ROIs.', ...
            'kind', 'parameter', ...
            'position', 5, ...
            'callType', 'namevalue', ...
            'default', 'VisualCtxAreas.roi', ...
            'dataType', 'char');

        info = PipelineManager.addInput(info, ...
            'b_UseMask', ...
            'parameter', ...
            'If true, use a logical mask during patch generation.', ...
            'kind', 'parameter', ...
            'position', 6, ...
            'callType', 'namevalue', ...
            'default', false, ...
            'allowed', [true false], ...
            'dataType', 'logical');

        info = PipelineManager.addInput(info, ...
            'MaskFile', ...
            'parameter', ...
            'Mask filename used when b_UseMask is true.', ...
            'kind', 'parameter', ...
            'position', 7, ...
            'callType', 'namevalue', ...
            'default', 'ImagingReferenceFrame.mat', ...
            'dataType', 'char');

        info = PipelineManager.addOutput(info, ...
            'outData', ...
            'ProcessedData', ...
            'data', ...
            'Visual Sign Map output UMT.', ...
            default_Output, ...
            1, ...
            'isData', true);

        info = PipelineManager.addOutput(info, ...
            'roiFile', ...
            'ProcessedData', ...
            'file', ...
            'DataViewer-compatible visual-area ROI file.', ...
            'VisualCtxAreas.roi', ...
            2, ...
            'isData', false, ...
            'isRequired', false);
    end
end

function roiFile = genVAmask(vsm, frameSize, SaveFolder, opts)
%GENVAMASK Generate a UMIT ROI file with segmented visual-area patches.

roiFile = '';

if opts.b_UseMask
    if isempty(fileparts(opts.MaskFile))
        opts.MaskFile = fullfile(SaveFolder, opts.MaskFile);
    end
    if ~isfile(opts.MaskFile)
        error('Umitoolbox:genVAmask:MissingMaskFile', ...
            'Mask file was not found: "%s".', opts.MaskFile);
    end
    a = load(opts.MaskFile, 'logical_mask');
    if isempty(fieldnames(a))
        error('Umitoolbox:genVAmask:MissingInput', ...
            'Variable "logical_mask" not found in mask file!');
    end
    disp(['Using logical mask from file: ' opts.MaskFile]);
    logical_mask = a.logical_mask;
    assert(isequal(size(logical_mask), frameSize), ...
        'Umitoolbox:genVAmask:InvalidInput', ...
        'The logical mask size is different from the frame size in data');
else
    logical_mask = true(frameSize);
end

thr = 1.5 * std(vsm(:));
rawMap = (imbinarize(abs(vsm), thr) & logical_mask);
rawMap = bwmorph(rawMap, 'open', inf);
[L, nPatch] = bwlabel(rawMap);

patchMap = zeros(size(rawMap), 'single');
for i = 1:nPatch
    patchMap = patchMap + bwmorph(imfill(L == i, 'holes'), 'close', inf);
end

total_area = bwmorph(imfill(~imerode(~patchMap, strel('diamond', 15)), 'holes'), 'majority', inf);
patchBorder = total_area - patchMap;
patchBorder = bwmorph(patchBorder, 'skel', inf);
patchBorder = bwmorph(patchBorder, 'spur', inf);
patches = imfill(patchBorder, 'holes') & ~patchBorder;
patches = bwlabel(patches, 4);

nCtxAreas = double(max(patches(:)));
if nCtxAreas == 0
    warning('Umitoolbox:genVSM:NoVisualPatches', ...
        ['No visual-area patches were detected. No ROI file was created; ' ...
         'an existing file with the requested name was left unchanged.']);
    return
end

colors = lines(nCtxAreas);
createdOn = datetime('now');
ROIs = struct([]);
for iArea = 1:nCtxAreas
    mask = patches == iArea;
    [pgon, verticesXY] = simplifyROIMaskPolygon(mask);
    thisROI = iCreateROIEntry(iArea, mask, pgon, verticesXY, ...
        colors(iArea, :), vsm, createdOn);
    if iArea == 1
        ROIs = repmat(thisROI, 1, nCtxAreas);
    else
        ROIs(iArea) = thisROI;
    end
end

ROIFile = createROIFile(frameSize, ...
    'entryName', 'VSM', ...
    'statsImage', single(vsm), ...
    'statsDescription', 'Visual sign map used to segment cortical-area ROIs.', ...
    'viewMode', 'normal', ...
    'ROIs', ROIs);

saveROIFile(fullfile(SaveFolder, opts.ROIFileName), ROIFile);
roiFile = opts.ROIFileName;
disp(['Visual-area ROIs saved as ' fullfile(SaveFolder, roiFile)]);
end

function roi = iCreateROIEntry(index, mask, pgon, verticesXY, color, vsm, timestamp)
%ICREATEROIENTRY Build one schema-valid visual-area ROI entry.

[rows, cols] = find(mask);
centroidXY = [mean(cols), mean(rows)];
values = double(vsm(mask));
nPixels = nnz(mask);

stats = struct( ...
    'computedOn', timestamp, ...
    'NPixels', nPixels, ...
    'areaPx2', nPixels, ...
    'areaMM2', [], ...
    'centroidXY_px', centroidXY, ...
    'centroidXY_mm', [], ...
    'distanceFromOrigin_px', norm(centroidXY - [1 1]), ...
    'distanceFromOrigin_mm', [], ...
    'spatialMean', mean(values, 'omitnan'), ...
    'spatialStd', std(values, 0, 'omitnan'), ...
    'spatialMedian', median(values, 'omitnan'), ...
    'spatialMin', min(values, [], 'omitnan'), ...
    'spatialMax', max(values, [], 'omitnan'));

roi = struct( ...
    'name', sprintf('CtxArea_%d', index), ...
    'type', 'polygon', ...
    'DOC', timestamp, ...
    'modifiedOn', timestamp, ...
    'color', double(color), ...
    'notes', '', ...
    'geometry', struct( ...
        'polyshape', pgon, ...
        'verticesXY_px', verticesXY, ...
        'ROIType', 'polygon', ...
        'ROIParameters', struct( ...
            'ROIType', 'polygon', ...
            'Position', verticesXY, ...
            'Vertices', verticesXY)), ...
    'mask', logical(mask), ...
    'stats', stats);
end

function fileName = iNormalizeROIFileName(value)
%INORMALIZEROIFILENAME Validate a SaveFolder-relative UMIT ROI filename.

fileName = strtrim(char(string(value)));
if isempty(fileName)
    error('Umitoolbox:genVSM:InvalidROIFileName', ...
        'ROIFileName must be non-empty.');
end

[folderPart, baseName, ext] = fileparts(fileName);
if ~isempty(folderPart) || isempty(baseName)
    error('Umitoolbox:genVSM:InvalidROIFileName', ...
        'ROIFileName must be a filename without folder components.');
end

if isempty(ext)
    ext = '.roi';
elseif ~strcmpi(ext, '.roi')
    error('Umitoolbox:genVSM:InvalidROIFileName', ...
        'ROIFileName must use the .roi extension.');
end

fileName = [baseName, ext];
end
