function schema = getROISchema(version)
%GETROISCHEMA Return centralized UMIT ROI schema definition.
%
%   schema = getROISchema()
%   schema = getROISchema(version)
%
%   Returns the schema definition used by createROIFile,
%   createROIEntry, validateROIFile, saveROIFile, and loadROIFile.
%
%   Inputs:
%       version - Numeric scalar schema version. Default: 1.
%
%   Output:
%       schema  - Structure containing required fields, allowed values,
%                 and the current ROI file schema name.
%
%   Notes:
%       - This is the first versioned .roi file schema.
%       - Retrocompatibility with pre-version ROI files is intentionally
%         not handled in version 1.

if nargin < 1 || isempty(version)
    version = 1;
end

if ~isnumeric(version) || ~isscalar(version)
    error('Umitoolbox:getROISchema:invalidVersion', ...
        'Schema version must be a numeric scalar.');
end

switch version
    case 1
        schema = struct();

        schema.schemaName = 'UMIT_ROI';
        schema.version = 1;

        schema.requiredTopFields = { ...
            'schemaName', ...
            'version', ...
            'createdOn', ...
            'modifiedOn', ...
            'imageInfo', ...
            'view', ...
            'statsImage', ...
            'ROIs'};

        schema.requiredImageInfoFields = { ...
            'dataFile', ...
            'entryName', ...
            'imageSizeYX', ...
            'coordinateSystem'};

        schema.requiredViewFields = { ...
            'originXY_px', ...
            'pixelSize_px_per_mm'};

        schema.requiredStatsImageFields = { ...
            'image', ...
            'description', ...
            'frameIndex', ...
            'viewMode', ...
            'eventCondition', ...
            'eventRepetition', ...
            'createdOn'};

        schema.requiredROIFields = { ...
            'name', ...
            'type', ...
            'DOC', ...
            'modifiedOn', ...
            'color', ...
            'notes', ...
            'geometry', ...
            'mask', ...
            'stats'};

        schema.requiredGeometryFields = { ...
            'polyshape', ...
            'verticesXY_px', ...
            'ROIType', ...
            'ROIParameters'};

        schema.requiredStatsFields = { ...
            'computedOn', ...
            'NPixels', ...
            'areaPx2', ...
            'areaMM2', ...
            'centroidXY_px', ...
            'centroidXY_mm', ...
            'distanceFromOrigin_px', ...
            'distanceFromOrigin_mm', ...
            'spatialMean', ...
            'spatialStd', ...
            'spatialMedian', ...
            'spatialMin', ...
            'spatialMax'};

        schema.allowedROITypes = {'rectangle', 'ellipse', 'polygon', 'polyshape'};
        schema.allowedCoordinateSystems = {'imageXY_px'};
        schema.allowedViewModes = {'', 'normal', 'event'};

    otherwise
        error('Umitoolbox:getROISchema:unsupportedVersion', ...
            'Unsupported ROI schema version: %g.', version);
end

end
