function validateDataParams(DataParams)
%VALIDATEDATAPARAMS Validate structure and field consistency of DataParams.
%
%   validateDataParams(DataParams)
%
%   Checks whether DataParams follows the expected schema and verifies
%   consistency of folder-global fields such as image size, origin, mask,
%   and registration metadata.
%
%   Required top-level fields:
%       schemaVersion
%       createdOn
%       lastModified
%       notes
%       view
%       mask
%       folders
%       registration
%       custom
%
%   Notes:
%       - This function throws an error when validation fails.
%       - Validation is intentionally permissive for optional fields.
%       - Registration metadata support both estimated-but-not-applied and
%         applied registration states.

if ~isstruct(DataParams) || ~isscalar(DataParams)
    error('validateDataParams:InvalidType', ...
        'DataParams must be a scalar struct.');
end

reqTopFields = { ...
    'schemaVersion', ...
    'createdOn', ...
    'lastModified', ...
    'notes', ...
    'view', ...
    'mask', ...
    'folders', ...
    'registration', ...
    'custom'};

for k = 1:numel(reqTopFields)
    if ~isfield(DataParams, reqTopFields{k})
        error('validateDataParams:MissingField', ...
            'Missing top-level field: DataParams.%s', reqTopFields{k});
    end
end

% =========================================================================
% View
% =========================================================================
if ~isstruct(DataParams.view) || ~isscalar(DataParams.view)
    error('validateDataParams:InvalidView', ...
        'DataParams.view must be a scalar struct.');
end

reqViewFields = { ...
    'pixelSize_px_per_mm', ...
    'origin_xy_px', ...
    'imageSizeYX', ...
    'axisConvention'};

for k = 1:numel(reqViewFields)
    if ~isfield(DataParams.view, reqViewFields{k})
        error('validateDataParams:MissingViewField', ...
            'Missing field: DataParams.view.%s', reqViewFields{k});
    end
end

if ~isempty(DataParams.view.pixelSize_px_per_mm)
    x = DataParams.view.pixelSize_px_per_mm;
    if ~isnumeric(x) || ~(isscalar(x) || numel(x) == 2) || ...
            any(~isfinite(x(:))) || any(x(:) <= 0)
        error('validateDataParams:InvalidPixelSize', ...
            ['DataParams.view.pixelSize_px_per_mm must be a positive ' ...
             'scalar or 2-element numeric vector.']);
    end
end

if ~isempty(DataParams.view.origin_xy_px)
    x = DataParams.view.origin_xy_px;
    if ~isnumeric(x) || numel(x) ~= 2 || any(~isfinite(x(:)))
        error('validateDataParams:InvalidOrigin', ...
            'DataParams.view.origin_xy_px must be a 2-element numeric vector [x y].');
    end
end

if ~isempty(DataParams.view.imageSizeYX)
    x = DataParams.view.imageSizeYX;
    if ~isnumeric(x) || numel(x) ~= 2 || any(~isfinite(x(:))) || ...
            any(x(:) <= 0) || any(mod(x(:),1) ~= 0)
        error('validateDataParams:InvalidImageSize', ...
            ['DataParams.view.imageSizeYX must be a positive integer ' ...
             '2-element vector [Ny Nx].']);
    end
end

if ~(ischar(DataParams.view.axisConvention) || ...
        (isstring(DataParams.view.axisConvention) && isscalar(DataParams.view.axisConvention)))
    error('validateDataParams:InvalidAxisConvention', ...
        'DataParams.view.axisConvention must be a char vector or string scalar.');
end

% =========================================================================
% Mask
% =========================================================================
if ~isstruct(DataParams.mask) || ~isscalar(DataParams.mask)
    error('validateDataParams:InvalidMask', ...
        'DataParams.mask must be a scalar struct.');
end

reqMaskFields = { ...
    'logical', ...
    'name', ...
    'description', ...
    'space', ...
    'createdOn', ...
    'source'};

for k = 1:numel(reqMaskFields)
    if ~isfield(DataParams.mask, reqMaskFields{k})
        error('validateDataParams:MissingMaskField', ...
            'Missing field: DataParams.mask.%s', reqMaskFields{k});
    end
end

if ~isempty(DataParams.mask.logical)
    if ~islogical(DataParams.mask.logical) || ndims(DataParams.mask.logical) ~= 2
        error('validateDataParams:InvalidMaskLogical', ...
            'DataParams.mask.logical must be a 2D logical array.');
    end

    if ~isempty(DataParams.view.imageSizeYX)
        if ~isequal(size(DataParams.mask.logical), DataParams.view.imageSizeYX)
            error('validateDataParams:MaskSizeMismatch', ...
                'DataParams.mask.logical size must match DataParams.view.imageSizeYX.');
        end
    end
end

% =========================================================================
% Folders
% =========================================================================
if ~isstruct(DataParams.folders) || ~isscalar(DataParams.folders)
    error('validateDataParams:InvalidFolders', ...
        'DataParams.folders must be a scalar struct.');
end

reqFolderFields = { ...
    'RawFolder', ...
    'RawFolderStatus', ...
    'RawFolderSetOn', ...
    'RawFolderSetBy'};

for k = 1:numel(reqFolderFields)
    if ~isfield(DataParams.folders, reqFolderFields{k})
        error('validateDataParams:MissingFoldersField', ...
            'Missing field: DataParams.folders.%s', reqFolderFields{k});
    end
end

if ~(ischar(DataParams.folders.RawFolder) || ...
        (isstring(DataParams.folders.RawFolder) && isscalar(DataParams.folders.RawFolder)))
    error('validateDataParams:InvalidRawFolder', ...
        'DataParams.folders.RawFolder must be a char vector or string scalar.');
end

rawFolderText = char(string(DataParams.folders.RawFolder));
if isempty(rawFolderText)
    error('validateDataParams:InvalidRawFolder', ...
        'DataParams.folders.RawFolder cannot be empty. Use ''Missing'' instead.');
end

if ~(ischar(DataParams.folders.RawFolderStatus) || ...
        (isstring(DataParams.folders.RawFolderStatus) && isscalar(DataParams.folders.RawFolderStatus)))
    error('validateDataParams:InvalidRawFolderStatus', ...
        'DataParams.folders.RawFolderStatus must be a char vector or string scalar.');
end

statusText = lower(strtrim(char(string(DataParams.folders.RawFolderStatus))));
validStatus = {'valid', 'missing', 'invalid'};
if ~ismember(statusText, validStatus)
    error('validateDataParams:InvalidRawFolderStatus', ...
        'DataParams.folders.RawFolderStatus must be ''valid'', ''missing'', or ''invalid''.');
end

if strcmpi(rawFolderText, 'Missing') && ~strcmp(statusText, 'missing')
    error('validateDataParams:RawFolderStatusMismatch', ...
        'DataParams.folders.RawFolderStatus must be ''missing'' when RawFolder is ''Missing''.');
end

if strcmp(statusText, 'missing') && ~strcmpi(rawFolderText, 'Missing')
    error('validateDataParams:RawFolderStatusMismatch', ...
        'DataParams.folders.RawFolder must be ''Missing'' when RawFolderStatus is ''missing''.');
end

if ~(isempty(DataParams.folders.RawFolderSetOn) || ...
        (isdatetime(DataParams.folders.RawFolderSetOn) && isscalar(DataParams.folders.RawFolderSetOn)))
    error('validateDataParams:InvalidRawFolderSetOn', ...
        'DataParams.folders.RawFolderSetOn must be empty or a scalar datetime.');
end

if ~(isempty(DataParams.folders.RawFolderSetBy) || ...
        ischar(DataParams.folders.RawFolderSetBy) || ...
        (isstring(DataParams.folders.RawFolderSetBy) && isscalar(DataParams.folders.RawFolderSetBy)))
    error('validateDataParams:InvalidRawFolderSetBy', ...
        'DataParams.folders.RawFolderSetBy must be empty, a char vector, or a string scalar.');
end

% =========================================================================
% Registration
% =========================================================================
if ~isstruct(DataParams.registration) || ~isscalar(DataParams.registration)
    error('validateDataParams:InvalidRegistration', ...
        'DataParams.registration must be a scalar struct.');
end

reqRegFields = { ...
    'isRegistered', ...
    'isReviewed', ...
    'tform', ...
    'transformType', ...
    'method', ...
    'referenceDescription', ...
    'referenceFile', ...
    'referenceImage', ...
    'createdOn', ...
    'source', ...
    'qcStatus', ...
    'qcWarning', ...
    'qcMetrics', ...
    'qcFigureFile', ...
    'qcPreviewImageFile', ...
    'appliedOn', ...
    'appliedBy', ...
    'confirmationMode', ...
    'notes', ...
    'resourceUUID'};

for k = 1:numel(reqRegFields)
    if ~isfield(DataParams.registration, reqRegFields{k})
        error('validateDataParams:MissingRegistrationField', ...
            'Missing field: DataParams.registration.%s', reqRegFields{k});
    end
end

if ~islogical(DataParams.registration.isRegistered) || ...
        ~isscalar(DataParams.registration.isRegistered)
    error('validateDataParams:InvalidIsRegistered', ...
        'DataParams.registration.isRegistered must be a scalar logical.');
end

if ~islogical(DataParams.registration.isReviewed) || ...
        ~isscalar(DataParams.registration.isReviewed)
    error('validateDataParams:InvalidIsReviewed', ...
        'DataParams.registration.isReviewed must be a scalar logical.');
end

if DataParams.registration.isRegistered && isempty(DataParams.registration.tform)
    error('validateDataParams:MissingTform', ...
        'DataParams.registration.tform cannot be empty when isRegistered is true.');
end

textRegFields = { ...
    'transformType', ...
    'method', ...
    'referenceDescription', ...
    'referenceFile', ...
    'createdOn', ...
    'source', ...
    'qcStatus', ...
    'qcWarning', ...
    'qcFigureFile', ...
    'qcPreviewImageFile', ...
    'appliedOn', ...
    'appliedBy', ...
    'confirmationMode', ...
    'notes', ...
    'resourceUUID'};

for k = 1:numel(textRegFields)
    fieldName = textRegFields{k};
    val = DataParams.registration.(fieldName);
    if ~(isempty(val) || ischar(val) || (isstring(val) && isscalar(val)))
        error('validateDataParams:InvalidRegistrationTextField', ...
            ['DataParams.registration.%s must be empty, a char vector, ' ...
             'or a string scalar.'], fieldName);
    end
end

if ~isempty(DataParams.registration.referenceImage)
    refImg = DataParams.registration.referenceImage;
    if ~(isnumeric(refImg) || islogical(refImg))
        error('validateDataParams:InvalidReferenceImage', ...
            'DataParams.registration.referenceImage must be numeric or logical.');
    end

    if ndims(refImg) ~= 2
        error('validateDataParams:InvalidReferenceImageDims', ...
            'DataParams.registration.referenceImage must be a 2D array.');
    end

    if ~isempty(DataParams.view.imageSizeYX)
        if ~isequal(size(refImg), DataParams.view.imageSizeYX)
            error('validateDataParams:ReferenceImageSizeMismatch', ...
                ['DataParams.registration.referenceImage size must match ' ...
                 'DataParams.view.imageSizeYX.']);
        end
    end
end

if ~isempty(DataParams.registration.tform)
    tf = DataParams.registration.tform;
    isValidTform = isa(tf, 'affine2d') || ...
                   isa(tf, 'projective2d') || ...
                   isa(tf, 'rigidtform2d') || ...
                   isa(tf, 'simtform2d') || ...
                   isa(tf, 'affinetform2d') || ...
                   isa(tf, 'images.geotrans.GeometricTransformation2D');

    if ~isValidTform
        error('validateDataParams:InvalidTform', ...
            ['DataParams.registration.tform is not a recognized 2D ' ...
             'geometric transform object.']);
    end
end

% -------------------------------------------------------------------------
% QC metrics
% -------------------------------------------------------------------------
if ~isstruct(DataParams.registration.qcMetrics) || ...
        ~isscalar(DataParams.registration.qcMetrics)
    error('validateDataParams:InvalidQCMetrics', ...
        'DataParams.registration.qcMetrics must be a scalar struct.');
end

reqQCMetricsFields = { ...
    'MIBefore', ...
    'MIAfter', ...
    'MIDelta', ...
    'translationXY_px', ...
    'rotationDeg', ...
    'scaleXY', ...
    'determinant'};

for k = 1:numel(reqQCMetricsFields)
    if ~isfield(DataParams.registration.qcMetrics, reqQCMetricsFields{k})
        error('validateDataParams:MissingQCMetricsField', ...
            'Missing field: DataParams.registration.qcMetrics.%s', ...
            reqQCMetricsFields{k});
    end
end

scalarMetricFields = {'MIBefore','MIAfter','MIDelta','rotationDeg','determinant'};
for k = 1:numel(scalarMetricFields)
    fieldName = scalarMetricFields{k};
    val = DataParams.registration.qcMetrics.(fieldName);
    if ~(isempty(val) || ...
            (isnumeric(val) && isscalar(val) && isfinite(val)))
        error('validateDataParams:InvalidQCMetricScalar', ...
            ['DataParams.registration.qcMetrics.%s must be empty or a ' ...
             'finite numeric scalar.'], fieldName);
    end
end

vecMetricFields = {'translationXY_px','scaleXY'};
for k = 1:numel(vecMetricFields)
    fieldName = vecMetricFields{k};
    val = DataParams.registration.qcMetrics.(fieldName);
    if ~(isempty(val) || ...
            (isnumeric(val) && numel(val) == 2 && all(isfinite(val(:)))))
        error('validateDataParams:InvalidQCMetricVector', ...
            ['DataParams.registration.qcMetrics.%s must be empty or a ' ...
             '2-element finite numeric vector.'], fieldName);
    end
end

% Optional sanity checks
if ~isempty(DataParams.registration.qcMetrics.scaleXY)
    if any(DataParams.registration.qcMetrics.scaleXY(:) <= 0)
        error('validateDataParams:InvalidScaleXY', ...
            'DataParams.registration.qcMetrics.scaleXY must contain positive values.');
    end
end

% -------------------------------------------------------------------------
% Cross-field consistency
% -------------------------------------------------------------------------
if DataParams.registration.isReviewed && isempty(DataParams.registration.tform)
    error('validateDataParams:ReviewedWithoutTform', ...
        'Registration cannot be marked as reviewed when tform is empty.');
end

if ~isempty(DataParams.registration.appliedOn) && ~DataParams.registration.isRegistered
    error('validateDataParams:AppliedOnWithoutRegistration', ...
        ['DataParams.registration.appliedOn cannot be populated when ' ...
         'isRegistered is false.']);
end

if ~isempty(DataParams.registration.appliedBy) && ~DataParams.registration.isRegistered
    error('validateDataParams:AppliedByWithoutRegistration', ...
        ['DataParams.registration.appliedBy cannot be populated when ' ...
         'isRegistered is false.']);
end

if ~isempty(DataParams.registration.confirmationMode) && ~DataParams.registration.isRegistered
    error('validateDataParams:ConfirmationModeWithoutRegistration', ...
        ['DataParams.registration.confirmationMode cannot be populated ' ...
         'when isRegistered is false.']);
end

end