function validateUMTStruct(data)
%VALIDATEUMTSTRUCT Validate UMIT derived-data structure for .umt files.
%
%   validateUMTStruct(data)
%
%   Validates whether the input structure follows the expected schema used
%   by .umt files generated by genUMTStruct / saveData.
%
%   Required fields:
%       data
%       obsID
%       b_hasEvents
%       b_hasMultipleMeasures
%       dataCategory
%
%   Notes:
%       - "data" must be a non-empty struct array.
%       - "obsID" must be a cell array of character vectors or strings with
%         one element per observation.
%       - "dataCategory" must be a scalar struct whose fields match the
%         fields present in data(1).
%
%   Error:
%       Throws an error if validation fails.

errID = 'Umitoolbox:validateUMTStruct:invalidInput';
errMsg = ['Operation aborted. Invalid UMT data structure. ' ...
          'See genUMTStruct.m documentation for details.'];

if ~isstruct(data) || ~isscalar(data)
    error(errID, errMsg);
end

% -- Required fields and valid categories for data type validation. Change
% these if new fields are to be added.
reqFields = {'data', 'obsID', 'b_hasEvents', 'b_hasMultipleMeasures', 'dataCategory'};
validCats = {'scalar', 'time-vector', 'map', 'Image-time-series', 'unknown'};


fn = fieldnames(data);

if ~all(ismember(reqFields, fn))
    error(errID, errMsg);
end

if ~isstruct(data.data) || isempty(data.data)
    error(errID, errMsg);
end

if ~iscell(data.obsID) || ~isvector(data.obsID) || ...
        ~all(cellfun(@(c) ischar(c) || (isstring(c) && isscalar(c)), data.obsID))
    error(errID, errMsg);
end

if ~islogical(data.b_hasEvents) || ~isscalar(data.b_hasEvents)
    error(errID, errMsg);
end

if ~islogical(data.b_hasMultipleMeasures) || ~isscalar(data.b_hasMultipleMeasures)
    error(errID, errMsg);
end

if ~isstruct(data.dataCategory) || ~isscalar(data.dataCategory)
    error(errID, errMsg);
end

if numel(data.data) ~= numel(data.obsID)
    error(errID, ...
        'Operation aborted. The number of observations in "data" and "obsID" must match.');
end

measureFields = fieldnames(data.data);
if isempty(measureFields)
    error(errID, errMsg);
end

for ii = 2:numel(data.data)
    if ~isequal(fieldnames(data.data(ii)), measureFields)
        error(errID, ...
            'Operation aborted. All elements of "data" must have the same fields.');
    end
end

catFields = fieldnames(data.dataCategory);
if ~isequal(sort(measureFields), sort(catFields))
    error(errID, ...
        ['Operation aborted. Fields in "dataCategory" must match the ' ...
         'measure fields in "data".']);
end


for ii = 1:numel(catFields)
    thisCat = data.dataCategory.(catFields{ii});
    if ~(ischar(thisCat) || (isstring(thisCat) && isscalar(thisCat)))
        error(errID, ...
            'Operation aborted. Each field in "dataCategory" must be a text label.');
    end

    thisCat = char(string(thisCat));
    if ~ismember(lower(thisCat), lower(validCats)) % Case-insensitive
        error(errID, ...
            'Operation aborted. Invalid data category "%s".', thisCat);
    end
end

if data.b_hasMultipleMeasures ~= (numel(measureFields) > 1)
    error(errID, ...
        ['Operation aborted. "b_hasMultipleMeasures" is inconsistent with ' ...
         'the number of fields in "data".']);
end
end