classdef TestImageReferenceStruct < matlab.unittest.TestCase
%TESTIMAGEREFERENCESTRUCT Unit tests for canonical ImageReference payloads.

    methods (Test)
        function testGenerateCanonicalReference(testCase)
        %TESTGENERATECANONICALREFERENCE Create and validate a base payload.

            projectUUID = lower(char(java.util.UUID.randomUUID()));
            subjectUUID = lower(char(java.util.UUID.randomUUID()));

            ImageReference = genImageReferenceStruct( ...
                reshape(single(1:20), 4, 5), ...
                'Name', 'Reference 1', ...
                'ProjectUUID', projectUUID, ...
                'ProjectName', 'Test Project', ...
                'SubjectUUID', subjectUUID, ...
                'SubjectID', 'Mouse_104', ...
                'Description', 'Unit-test reference', ...
                'SourceType', 'unit-test', ...
                'CreatedBy', 'TestImageReferenceStruct');

            testCase.verifyClass(ImageReference.image, 'single');
            testCase.verifyEqual(ImageReference.imageSizeYX, [4 5]);
            testCase.verifyFalse(ImageReference.wasManuallyTransformed);
            testCase.verifyTrue(isnat( ...
                ImageReference.manualTransformAppliedOn));
            testCase.verifyWarningFree(@() ...
                validateImageReferenceStruct(ImageReference));
        end

        function testNonFinitePixelsBecomeZero(testCase)
        %TESTNONFINITEPIXELSBECOMEZERO Sanitize canonical image payload.

            imageData = single([1 NaN; Inf 4]);
            ImageReference = testCase.createReference(imageData);

            testCase.verifyEqual(ImageReference.image, ...
                single([1 0; 0 4]));
        end

        function testSessionIdentityMustBeComplete(testCase)
        %TESTSESSIONIDENTITYMUSTBECOMPLETE Require paired session identity.

            testCase.verifyError(@() genImageReferenceStruct( ...
                ones(3, 3), ...
                'Name', 'Reference', ...
                'ProjectUUID', ...
                lower(char(java.util.UUID.randomUUID())), ...
                'ProjectName', 'Test Project', ...
                'SubjectUUID', ...
                lower(char(java.util.UUID.randomUUID())), ...
                'SubjectID', 'Mouse_104', ...
                'SessionID', 'Session_01'), ...
                'Umitoolbox:genImageReferenceStruct:invalidInput');
        end

        function testManualTransformRequiresTransform(testCase)
        %TESTMANUALTRANSFORMREQUIRESTRANSFORM Enforce edit provenance.

            testCase.verifyError(@() genImageReferenceStruct( ...
                ones(3, 3), ...
                'Name', 'Reference', ...
                'ProjectUUID', ...
                lower(char(java.util.UUID.randomUUID())), ...
                'ProjectName', 'Test Project', ...
                'SubjectUUID', ...
                lower(char(java.util.UUID.randomUUID())), ...
                'SubjectID', 'Mouse_104', ...
                'WasManuallyTransformed', true), ...
                'Umitoolbox:genImageReferenceStruct:invalidInput');
        end

        function testManualTransformPayload(testCase)
        %TESTMANUALTRANSFORMPAYLOAD Store transform provenance.

            parentUUID = lower(char(java.util.UUID.randomUUID()));
            tform = affine2d([1 0 0; 0 1 0; 2 -3 1]);

            ImageReference = genImageReferenceStruct( ...
                ones(3, 3), ...
                'Name', 'Edited Reference', ...
                'ProjectUUID', ...
                lower(char(java.util.UUID.randomUUID())), ...
                'ProjectName', 'Test Project', ...
                'SubjectUUID', ...
                lower(char(java.util.UUID.randomUUID())), ...
                'SubjectID', 'Mouse_104', ...
                'ParentResourceUUID', parentUUID, ...
                'WasManuallyTransformed', true, ...
                'ManualTransformTform', tform, ...
                'ManualTransformNote', 'Translated for alignment.');

            testCase.verifyTrue(ImageReference.wasManuallyTransformed);
            testCase.verifyClass( ...
                ImageReference.manualTransformTform, 'affine2d');
            testCase.verifyEqual( ...
                ImageReference.parentResourceUUID, parentUUID);
            testCase.verifyFalse(isnat( ...
                ImageReference.manualTransformAppliedOn));
        end

        function testRejectUnknownField(testCase)
        %TESTREJECTUNKNOWNFIELD Keep the payload schema strict.

            ImageReference = testCase.createReference(ones(3, 3));
            ImageReference.unmanagedPath = 'C:\invalid';

            testCase.verifyError(@() ...
                validateImageReferenceStruct(ImageReference), ...
                'Umitoolbox:validateImageReferenceStruct:invalidInput');
        end

        function testRejectImageSizeMismatch(testCase)
        %TESTREJECTIMAGESIZEMISMATCH Detect inconsistent image metadata.

            ImageReference = testCase.createReference(ones(3, 3));
            ImageReference.imageSizeYX = [3 4];

            testCase.verifyError(@() ...
                validateImageReferenceStruct(ImageReference), ...
                'Umitoolbox:validateImageReferenceStruct:invalidInput');
        end
    end

    methods (Access = private)
        function ImageReference = createReference(~, imageData)
        %CREATEREFERENCE Create one canonical test payload.

            ImageReference = genImageReferenceStruct( ...
                imageData, ...
                'Name', 'Reference', ...
                'ProjectUUID', ...
                lower(char(java.util.UUID.randomUUID())), ...
                'ProjectName', 'Test Project', ...
                'SubjectUUID', ...
                lower(char(java.util.UUID.randomUUID())), ...
                'SubjectID', 'Mouse_104', ...
                'CreatedBy', 'TestImageReferenceStruct');
        end
    end
end
